import type {
  MemoryFeatureV1,
  SaveFieldFeatureV1,
  SolithDefinitionV1,
  SolithTargetMetadataV1,
} from './schema.v1.js';

/**
 * Fixed banner text emitted by every export. Recognized by the compiler
 * (compile-yaml.v1.ts) so it is never re-captured as provenance on import —
 * only genuinely novel comments (headerLines, evidence, session notes) are.
 */
export const YAML_EXPORT_BANNER_LINES = [
  'Solith Definition v1 — generated by Solith',
  'Game control, saves, and recovery.',
  'Review offsets, paths, and fingerprints before distributing.',
] as const;

export interface YamlExportOptions {
  /** Extra header lines inserted after the standard banner. */
  headerLines?: string[];
  /** Discovery evidence snippet for the exported save field. */
  discoveryEvidence?: string;
  /** Live-memory session address note (not distributed — review before compile). */
  sessionAddressNote?: string;
}

function yamlString(value: string): string {
  if (/[:#{}[\],&*!|>'"%@`]|^\s|-\s|\n/.test(value)) {
    return JSON.stringify(value);
  }
  return value;
}

function yamlNumber(value: number): string {
  return Number.isFinite(value) ? String(value) : '0';
}

function yamlBool(value: boolean): string {
  return value ? 'true' : 'false';
}

function indentBlock(lines: string[], spaces: number): string[] {
  const pad = ' '.repeat(spaces);
  return lines.map((line) => (line.length > 0 ? `${pad}${line}` : line));
}

/** Renders a string-list field either inline-empty (`key: []`) or as a block list. */
function renderStringArray(key: string, values: string[], spaces: number): string[] {
  if (values.length === 0) {
    return [`${key}: []`];
  }
  return [`${key}:`, ...indentBlock(values.map((v) => `- ${yamlString(v)}`), spaces)];
}

function renderTargetMetadataEntry(entry: SolithTargetMetadataV1): string[] {
  const lines = [
    `- targetId: ${yamlString(entry.targetId)}`,
    `  launcher: ${yamlString(entry.launcher)}`,
    `  executableName: ${yamlString(entry.executableName)}`,
  ];
  if (entry.executableSha256) {
    lines.push(`  executableSha256: ${yamlString(entry.executableSha256)}`);
  }
  if (entry.executableHashPrefixes && entry.executableHashPrefixes.length > 0) {
    lines.push(
      '  executableHashPrefixes:',
      ...indentBlock(entry.executableHashPrefixes.map((v) => `- ${yamlString(v)}`), 4),
    );
  }
  lines.push(
    `  moduleName: ${yamlString(entry.moduleName)}`,
    `  packaging: ${yamlString(entry.packaging)}`,
    `  accessModel: ${yamlString(entry.accessModel)}`,
  );
  if (entry.certificationLevel) {
    lines.push(`  certificationLevel: ${yamlString(entry.certificationLevel)}`);
  }
  return lines;
}

function renderSaveField(field: SaveFieldFeatureV1, evidence?: string): string[] {
  const lines = [
    `- id: ${yamlString(field.id)}`,
    `  name: ${yamlString(field.name)}`,
    `  category: ${yamlString(field.category)}`,
    `  dataType: ${yamlString(field.dataType)}`,
    '  mapping:',
  ];
  if (field.mapping.searchKey) {
    lines.push(`    searchKey: ${yamlString(field.mapping.searchKey)}`);
  }
  if (field.mapping.hexOffset) {
    lines.push(`    hexOffset: ${yamlString(field.mapping.hexOffset)}`);
  }
  if (field.mapping.query) {
    lines.push(`    query: ${yamlString(field.mapping.query)}`);
  }
  if (evidence) {
    lines.push(`  # evidence: ${evidence}`);
  }
  return lines;
}

function renderMemoryFeature(feature: MemoryFeatureV1, sessionNote?: string): string[] {
  const lines = [
    `- id: ${yamlString(feature.id)}`,
    `  name: ${yamlString(feature.name)}`,
    `  category: ${yamlString(feature.category)}`,
    `  type: ${yamlString(feature.type)}`,
    `  dataType: ${yamlString(feature.dataType)}`,
    `  defaultValue: ${
      typeof feature.defaultValue === 'boolean'
        ? yamlBool(feature.defaultValue)
        : yamlNumber(feature.defaultValue)
    }`,
    '  resolution:',
    `    moduleName: ${yamlString(feature.resolution.moduleName)}`,
  ];
  if (feature.resolution.signature) {
    lines.push(`    signature: ${yamlString(feature.resolution.signature)}`);
  }
  if (feature.resolution.baseOffset) {
    lines.push(`    baseOffset: ${JSON.stringify(String(feature.resolution.baseOffset))}`);
  }
  if (feature.resolution.pointerChain && feature.resolution.pointerChain.length > 0) {
    lines.push(`    pointerChain: [${feature.resolution.pointerChain.join(', ')}]`);
  }
  if (feature.certificationLevel) {
    lines.push(`  certificationLevel: ${yamlString(feature.certificationLevel)}`);
  }
  if (sessionNote) {
    lines.push(`  # session-only address captured during export: ${sessionNote}`);
    lines.push('  # Replace with restart-stable pointer chain or AOB before distributing this definition.');
  }
  return lines;
}

/**
 * Serialize a schema.v1 definition to human-readable YAML with review comments.
 * O.3 will add a parser/compiler — this exporter is authoring-oriented only.
 */
export function serializeDefinitionToYaml(
  definition: SolithDefinitionV1,
  options: YamlExportOptions = {},
): string {
  const lines: string[] = [
    ...YAML_EXPORT_BANNER_LINES.map((line) => `# ${line}`),
    ...(options.headerLines ?? []),
    ...(definition.provenanceNotes ?? []).map((note) => `# ${note}`),
    '',
    `schemaVersion: ${definition.schemaVersion}`,
    `id: ${yamlString(definition.id)}`,
    `title: ${yamlString(definition.title)}`,
    `gameVersion: ${yamlString(definition.gameVersion)}`,
    ...(definition.targetSHA256 ? [`targetSHA256: ${yamlString(definition.targetSHA256)}`] : []),
    ...renderStringArray('executableHashPrefixes', definition.executableHashPrefixes ?? [], 2),
    `author: ${yamlString(definition.author)}`,
    ...(definition.certificationLevel
      ? [`certificationLevel: ${yamlString(definition.certificationLevel)}`]
      : []),
    '',
    'safety:',
    `  requiresApproval: ${yamlBool(definition.safety.requiresApproval)}`,
    `  requiresOfflineConfirm: ${yamlBool(definition.safety.requiresOfflineConfirm)}`,
    `  verificationStatus: ${yamlString(definition.safety.verificationStatus)}`,
    '',
    'target:',
    '  executables:',
    ...definition.target.executables.map((exe) => `    - ${yamlString(exe)}`),
    `  arch: ${yamlString(definition.target.arch)}`,
  ];

  if (definition.targetMetadata && definition.targetMetadata.length > 0) {
    lines.push('', 'targetMetadata:');
    for (const entry of definition.targetMetadata) {
      lines.push(...indentBlock(renderTargetMetadataEntry(entry), 2));
    }
  }

  if (definition.connectionBaseline !== undefined) {
    lines.push(`connectionBaseline: ${definition.connectionBaseline}`);
  }

  if (definition.saveEditor) {
    lines.push(
      '',
      'saveEditor:',
      `  defaultDirectory: ${yamlString(definition.saveEditor.defaultDirectory)}`,
      `  extension: ${yamlString(definition.saveEditor.extension)}`,
      `  format: ${yamlString(definition.saveEditor.format)}`,
      '  saveFields:',
    );
    for (const field of definition.saveEditor.saveFields) {
      lines.push(...indentBlock(renderSaveField(field, options.discoveryEvidence), 4));
    }
  }

  if (definition.memoryFeatures && definition.memoryFeatures.length > 0) {
    lines.push('', 'memoryFeatures:');
    for (const feature of definition.memoryFeatures) {
      lines.push(...indentBlock(renderMemoryFeature(feature, options.sessionAddressNote), 2));
    }
  }

  lines.push('');
  return lines.join('\n');
}
