import type {
  MemoryFeatureV1,
  SaveFieldFeatureV1,
  SolithDefinitionV1,
} from './schema.v1.js';

export interface YamlExportOptions {
  /** Extra header lines inserted after the standard banner. */
  headerLines?: string[];
  /** Discovery evidence snippet for the exported save field. */
  discoveryEvidence?: string;
  /** Live-memory session address note (not distributed — review before compile). */
  sessionAddressNote?: string;
}

function yamlString(value: string): string {
  if (/[:#{}[\],&*!|>'"%@`]|^\s|-\s|\n/.test(value)) {
    return JSON.stringify(value);
  }
  return value;
}

function yamlNumber(value: number): string {
  return Number.isFinite(value) ? String(value) : '0';
}

function yamlBool(value: boolean): string {
  return value ? 'true' : 'false';
}

function indentBlock(lines: string[], spaces: number): string[] {
  const pad = ' '.repeat(spaces);
  return lines.map((line) => (line.length > 0 ? `${pad}${line}` : line));
}

function renderSaveField(field: SaveFieldFeatureV1, evidence?: string): string[] {
  const lines = [
    `- id: ${yamlString(field.id)}`,
    `  name: ${yamlString(field.name)}`,
    `  category: ${yamlString(field.category)}`,
    `  dataType: ${yamlString(field.dataType)}`,
    '  mapping:',
  ];
  if (field.mapping.searchKey) {
    lines.push(`    searchKey: ${yamlString(field.mapping.searchKey)}`);
  }
  if (field.mapping.hexOffset) {
    lines.push(`    hexOffset: ${yamlString(field.mapping.hexOffset)}`);
  }
  if (field.mapping.query) {
    lines.push(`    query: ${yamlString(field.mapping.query)}`);
  }
  if (evidence) {
    lines.push(`  # evidence: ${evidence}`);
  }
  return lines;
}

function renderMemoryFeature(feature: MemoryFeatureV1, sessionNote?: string): string[] {
  const lines = [
    `- id: ${yamlString(feature.id)}`,
    `  name: ${yamlString(feature.name)}`,
    `  category: ${yamlString(feature.category)}`,
    `  type: ${yamlString(feature.type)}`,
    `  dataType: ${yamlString(feature.dataType)}`,
    `  defaultValue: ${
      typeof feature.defaultValue === 'boolean'
        ? yamlBool(feature.defaultValue)
        : yamlNumber(feature.defaultValue)
    }`,
    '  resolution:',
    `    moduleName: ${yamlString(feature.resolution.moduleName)}`,
  ];
  if (feature.resolution.signature) {
    lines.push(`    signature: ${yamlString(feature.resolution.signature)}`);
  }
  if (feature.resolution.baseOffset) {
    lines.push(`    baseOffset: ${yamlString(feature.resolution.baseOffset)}`);
  }
  if (feature.resolution.pointerChain && feature.resolution.pointerChain.length > 0) {
    lines.push(`    pointerChain: [${feature.resolution.pointerChain.join(', ')}]`);
  }
  if (sessionNote) {
    lines.push(`  # session-only address captured during export: ${sessionNote}`);
    lines.push('  # Replace with restart-stable pointer chain or AOB before distributing this definition.');
  }
  return lines;
}

/**
 * Serialize a schema.v1 definition to human-readable YAML with review comments.
 * O.3 will add a parser/compiler — this exporter is authoring-oriented only.
 */
export function serializeDefinitionToYaml(
  definition: SolithDefinitionV1,
  options: YamlExportOptions = {},
): string {
  const lines: string[] = [
    '# Solith Definition v1 — generated by Solith',
    '# Game control, saves, and recovery.',
    '# Review offsets, paths, and fingerprints before distributing.',
    ...(options.headerLines ?? []),
    '',
    `schemaVersion: ${definition.schemaVersion}`,
    `id: ${yamlString(definition.id)}`,
    `title: ${yamlString(definition.title)}`,
    `gameVersion: ${yamlString(definition.gameVersion)}`,
    'executableHashPrefixes: []',
    `author: ${yamlString(definition.author)}`,
    '',
    'safety:',
    `  requiresApproval: ${yamlBool(definition.safety.requiresApproval)}`,
    `  requiresOfflineConfirm: ${yamlBool(definition.safety.requiresOfflineConfirm)}`,
    `  verificationStatus: ${yamlString(definition.safety.verificationStatus)}`,
    '',
    'target:',
    '  executables:',
    ...definition.target.executables.map((exe) => `    - ${yamlString(exe)}`),
    `  arch: ${yamlString(definition.target.arch)}`,
  ];

  if (definition.connectionBaseline !== undefined) {
    lines.push(`connectionBaseline: ${definition.connectionBaseline}`);
  }

  if (definition.saveEditor) {
    lines.push(
      '',
      'saveEditor:',
      `  defaultDirectory: ${yamlString(definition.saveEditor.defaultDirectory)}`,
      `  extension: ${yamlString(definition.saveEditor.extension)}`,
      `  format: ${yamlString(definition.saveEditor.format)}`,
      '  saveFields:',
    );
    for (const field of definition.saveEditor.saveFields) {
      lines.push(...indentBlock(renderSaveField(field, options.discoveryEvidence), 4));
    }
  }

  if (definition.memoryFeatures && definition.memoryFeatures.length > 0) {
    lines.push('', 'memoryFeatures:');
    for (const feature of definition.memoryFeatures) {
      lines.push(...indentBlock(renderMemoryFeature(feature, options.sessionAddressNote), 2));
    }
  }

  lines.push('');
  return lines.join('\n');
}
