/**
 * Multi-game cheat registry across 7 games — presentation / session UX only.
 *
 * Phase 4: capability execution is schema.v1-only (bundled definitions + dual-read
 * removal). Do NOT add new titles here as the execute SoT. Author schema.v1 YAML/JSON
 * instead. ALL_GAMES remains for MultiGame / Overlay presentation and as material for
 * scan_unknown feature materialization in bundled-definition-seed.
 */

import type { GameConfig, CheatDefinition, CheatSource, GameImageUrls } from './types.js';

/**
 * Builds Steam CDN image URLs from a known AppID.
 * Steam's CDN is publicly hotlinkable (used by countless launchers/overlays).
 * If the AppID is wrong/unavailable, the UI falls back to a generated gradient
 * placeholder (see GameSpecificCheatMenu's onError handling) — this is a
 * best-effort enhancement, not a hard dependency.
 */
function steamImages(appId: number): GameImageUrls {
  const base = `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}`;
  return {
    steamAppId: appId,
    headerUrl: `${base}/header.jpg`,
    coverUrl: `${base}/library_600x900_2x.jpg`,
    iconUrl: `${base}/capsule_231x87.jpg`,
  };
}

const COMMON_SOURCES = {
  communityCatalog: (url?: string): CheatSource => ({
    name: 'Community Catalog',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
  communityResearch: (url?: string): CheatSource => ({
    name: 'Community Research',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
  modRepository: (url?: string): CheatSource => ({
    name: 'Mod Repository',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
  smapi: (url?: string): CheatSource => ({
    name: 'SMAPI',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
  official: (url?: string): CheatSource => ({
    name: 'Official',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
};

/**
 * Builds a CheatDefinition with common defaults filled in, so individual
 * entries only need to state what's actually distinct about that cheat.
 * `requiresDiscovery` defaults to true because every memory-scan game here
 * is affected by ASLR — a cheat is only `false` when a stable address has
 * actually been confirmed (see Palworld's 'gold-amount').
 */
function mk(
  def: Pick<CheatDefinition, 'id' | 'name' | 'description' | 'category' | 'valueType'> &
    Partial<CheatDefinition>,
): CheatDefinition {
  return {
    requiresDiscovery: true,
    verified: true,
    riskLevel: 'safe',
    source: COMMON_SOURCES.communityCatalog(),
    tags: [],
    ...def,
  };
}

/** Community trainer listing reference — option names only, not verified pointer paths. */
function fromFlingListing(
  slug: string,
  hotkey: string,
  def: Pick<CheatDefinition, 'id' | 'name' | 'description' | 'category' | 'valueType'> &
    Partial<CheatDefinition>,
): CheatDefinition {
  return {
    requiresDiscovery: true,
    verified: false,
    riskLevel: 'medium',
    source: {
      name: 'Remote Listing',
      url: `https://flingtrainer.com/trainer/${slug}-trainer/`,
      verified: false,
      lastChecked: new Date('2026-07-13'),
    },
    notes: `FLiNG reference hotkey: ${hotkey}. Metadata only — no third-party trainer binary.`,
    tags: [],
    ...def,
  };
}

const CRIMSON_DESERT_CT = 'fixtures/community-ct/CrimsonDesert.CT';

/** OpenCheatTables / community CT metadata — Auto Assembler scripts are reference-only in Solith. */
function fromCommunityCt(
  def: Pick<CheatDefinition, 'id' | 'name' | 'description' | 'category' | 'valueType'> &
    Partial<CheatDefinition>,
): CheatDefinition {
  return {
    requiresDiscovery: true,
    verified: false,
    riskLevel: 'medium',
    source: {
      name: 'Community',
      url: CRIMSON_DESERT_CT,
      verified: false,
      lastChecked: new Date('2026-07-13'),
    },
    notes:
      'Community CT (OpenCheatTables). Auto Assembler in CE — Solith stores names/categories until pointer paths are verified.',
    tags: ['community-ct'],
    ...def,
  };
}

// ============================================================================
// PALWORLD (48 cheats — aligned with FLiNG v1.0+ listing)
// ============================================================================

const palworldCheats: CheatDefinition[] = [
  // Player
  {
    id: 'infinite-player-health',
    name: 'Infinite Player Health',
    description: 'Prevents player HP loss from all damage sources',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'infinite-stamina',
    name: 'Infinite Stamina',
    description: 'Prevents stamina depletion during activities',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'infinite-satiety',
    name: 'Infinite Satiety',
    description: 'Prevents hunger loss',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 100,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  // Inventory
  {
    id: 'gold-amount',
    name: 'Gold',
    description: 'Modify current gold amount (0x218f743a954, 0x218ff263f30)',
    category: 'Inventory',
    valueType: 'int32',
    infiniteValue: 999999,
    normalValues: { min: 0, max: 999999 },
    requiresDiscovery: false,
    tags: ['currency', 'discoverable'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
    notes: 'Stable addresses: 0x218f743a954 or 0x218ff263f30',
  },
  {
    id: 'no-item-weight',
    name: 'No Item Weight Limit',
    description: 'Carry unlimited weight in inventory',
    category: 'Inventory',
    valueType: 'int32',
    infiniteValue: 0,
    requiresDiscovery: true,
    tags: ['infinity', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  // Game
  {
    id: 'instant-capture',
    name: '100% Capture Chance',
    description: 'Guaranteed capture on thrown ball',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 100,
    requiresDiscovery: true,
    tags: ['toggle', 'gameplay'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'all-pals-rare',
    name: 'All Pals Are Rare',
    description: 'Encounter rare Pals at normal spawn rates',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 1,
    requiresDiscovery: true,
    tags: ['toggle', 'gameplay'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'instant-work-progress',
    name: 'Instant Work Progress',
    description: 'Palbox and workbench tasks complete instantly',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 100,
    requiresDiscovery: true,
    tags: ['toggle', 'productivity'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'no-crafting-requirements',
    name: 'No Crafting Requirements',
    description: 'Craft without materials',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 1,
    requiresDiscovery: true,
    tags: ['toggle', 'bypass'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'no-building-requirements',
    name: 'No Building Requirements',
    description: 'Build structures without materials',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 1,
    requiresDiscovery: true,
    tags: ['toggle', 'bypass'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  // Physics
  {
    id: 'instant-acceleration',
    name: 'Instant Acceleration',
    description: 'Reach max speed immediately (no acceleration time)',
    category: 'Physics',
    valueType: 'float',
    infiniteValue: 10,
    requiresDiscovery: true,
    tags: ['multiplier', 'movement'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'sprint-speed-multiplier',
    name: 'Set Sprint Speed Multiplier',
    description: 'Modify sprint/run speed',
    category: 'Physics',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0, max: 10 },
    requiresDiscovery: true,
    tags: ['multiplier', 'movement'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'jump-height-multiplier',
    name: 'Set Jump Height Multiplier',
    description: 'Modify how high player jumps',
    category: 'Physics',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0, max: 10 },
    requiresDiscovery: true,
    tags: ['multiplier', 'movement'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  // Weapons
  {
    id: 'infinite-weapon-durability',
    name: 'Infinite Weapon Durability',
    description: 'Weapons never break or degrade',
    category: 'Weapons',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'infinite-pal-health',
    name: 'Infinite Pal Health',
    description: 'Active Pal takes no damage',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite', 'toggle'],
  }),
  mk({
    id: 'temperature-normal',
    name: 'Temperature Always Normal',
    description: 'Never affected by environmental temperature',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'environment'],
  }),
  mk({
    id: 'infinite-sanity',
    name: 'Infinite Sanity',
    description: 'Sanity never decreases',
    category: 'Stats',
    valueType: 'int32',
    infiniteValue: 100,
    tags: ['infinite', 'toggle'],
  }),
  mk({
    id: 'set-stat-points',
    name: 'Set Stat Points',
    description: 'Modify available player stat points',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 9999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-technology-points',
    name: 'Set Technology Points',
    description: 'Add/set technology research points',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 9999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-ancient-technology-points',
    name: 'Set Ancient Technology Points',
    description: 'Add/set ancient tech points for special research',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 9999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-lifmunk-effigies',
    name: 'Set Lifmunk Effigies',
    description: 'Modify Lifmunk Effigies currency/count',
    category: 'Inventory',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 99999 },
    tags: ['stepper', 'currency'],
  }),
  mk({
    id: 'set-experience-multiplier',
    name: 'Set Experience Multiplier',
    description: 'Modify how much EXP you gain per action',
    category: 'Stats',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 20 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'infinite-weapon-durability-2',
    name: '[Overheat Rifle] No Heat',
    description: 'Prevent rifle overheat mechanic',
    category: 'Weapons',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'no-reload',
    name: 'No Reload',
    description: 'Remove ammunition/reload requirements',
    category: 'Weapons',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'set-loot-drop-multiplier',
    name: 'Set Loot Drop Multiplier',
    description: 'Modify enemy loot drop rate',
    category: 'Enemies',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 10 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-walking-speed-multiplier',
    name: 'Set Walking Speed Multiplier',
    description: 'Modify walking pace',
    category: 'Physics',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.5, max: 10 },
    tags: ['stepper', 'multiplier'],
    notes: 'FLiNG reference hotkey: Alt+Num - (Set Player Speed)',
  }),
  fromFlingListing('palworld', 'Num 1', {
    id: 'god-mode-ignore-hits',
    name: 'God Mode / Ignore Hits',
    description: 'Ignore incoming damage hits while still allowing other effects',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'infinite'],
  }),
  fromFlingListing('palworld', 'Num 2', {
    id: 'lock-health',
    name: 'Lock Health',
    description: 'Freeze current health at its present value',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromFlingListing('palworld', 'Num 3', {
    id: 'infinite-shield',
    name: 'Infinite Shield',
    description: 'Shield bar stays full or regenerates instantly',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite', 'toggle'],
  }),
  fromFlingListing('palworld', 'Num 4', {
    id: 'max-food',
    name: 'Max Food',
    description: 'Keep hunger/food meter topped off',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 100,
    tags: ['infinite', 'toggle'],
  }),
  fromFlingListing('palworld', 'Num 6', {
    id: 'stealth-mode',
    name: 'Stealth Mode',
    description: 'Reduce enemy detection while moving near hostile Pals',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromFlingListing('palworld', 'Num 0', {
    id: 'hundred-percent-drop-rate',
    name: '100% Drop Rate',
    description: 'Enemies always drop loot on defeat',
    category: 'Enemies',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromFlingListing('palworld', 'Num *', {
    id: 'super-damage-one-hit-kills',
    name: 'Super Damage / One Hit Kills',
    description: 'Outgoing attacks deal lethal damage',
    category: 'Weapons',
    valueType: 'float',
    infiniteValue: 9999,
    tags: ['multiplier'],
  }),
  fromFlingListing('palworld', 'Num +', {
    id: 'damage-multiplier',
    name: 'Damage Multiplier',
    description: 'Scale outgoing weapon and skill damage',
    category: 'Weapons',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 50 },
    tags: ['stepper', 'multiplier'],
  }),
  fromFlingListing('palworld', 'Num -', {
    id: 'defense-multiplier',
    name: 'Defense Multiplier',
    description: 'Scale incoming damage reduction',
    category: 'Player',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 50 },
    tags: ['stepper', 'multiplier'],
  }),
  fromFlingListing('palworld', 'Ctrl+Num 2', {
    id: 'edit-items-amount',
    name: 'Edit Items Amount',
    description: 'Modify stack size of the selected inventory item',
    category: 'Inventory',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 0, max: 99999 },
    tags: ['stepper'],
  }),
  fromFlingListing('palworld', 'Ctrl+Num 4', {
    id: 'infinite-equipment-durability',
    name: 'Infinite Equipment Durability',
    description: 'All equipped gear avoids durability loss',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['infinite', 'toggle'],
  }),
  fromFlingListing('palworld', 'Ctrl+Num 5', {
    id: 'food-wont-spoil',
    name: "Food Won't Spoil",
    description: 'Inventory food items never spoil or lose freshness',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromFlingListing('palworld', 'Ctrl+Num 8', {
    id: 'fast-crafting-building',
    name: 'Fast Crafting & Building',
    description: 'Accelerate crafting queues and structure placement',
    category: 'Game',
    valueType: 'float',
    defaultValue: 5.0,
    normalValues: { min: 1, max: 100 },
    tags: ['multiplier'],
  }),
  fromFlingListing('palworld', 'Ctrl+Num 9', {
    id: 'freeze-daytime',
    name: 'Freeze Daytime',
    description: 'Stop the in-game clock from advancing',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'time'],
  }),
  fromFlingListing('palworld', 'Ctrl+Num 0', {
    id: 'time-pass-speed',
    name: 'Time Pass Speed',
    description: 'Adjust how quickly day/night cycles advance',
    category: 'Game',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0, max: 20 },
    tags: ['stepper', 'time'],
  }),
  fromFlingListing('palworld', 'Ctrl+Num.', {
    id: 'set-game-speed',
    name: 'Set Game Speed',
    description: 'Global simulation speed multiplier',
    category: 'Game',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 5 },
    tags: ['stepper', 'time'],
  }),
  fromFlingListing('palworld', 'Alt+Num 1', {
    id: 'pal-lock-health',
    name: 'Pal: Lock Health',
    description: 'Freeze active Pal health at current value',
    category: 'Stats',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromFlingListing('palworld', 'Alt+Num 2', {
    id: 'pal-max-food',
    name: 'Pal: Max Food',
    description: 'Keep active Pal hunger topped off',
    category: 'Stats',
    valueType: 'int32',
    infiniteValue: 100,
    tags: ['infinite', 'toggle'],
  }),
  fromFlingListing('palworld', 'Alt+Num 3', {
    id: 'pal-max-san',
    name: 'Pal: Max San',
    description: 'Keep active Pal sanity at maximum',
    category: 'Stats',
    valueType: 'int32',
    infiniteValue: 100,
    tags: ['infinite', 'toggle'],
  }),
  fromFlingListing('palworld', 'Alt+Num 4', {
    id: 'pal-infinite-stamina',
    name: 'Pal: Infinite Stamina',
    description: 'Active Pal stamina never depletes',
    category: 'Stats',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite', 'toggle'],
  }),
  fromFlingListing('palworld', 'Alt+Num 5', {
    id: 'pal-instant-skill-cooldown',
    name: 'Pal: Instant Skill Cooldown',
    description: 'Partner skills recharge immediately',
    category: 'Stats',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromFlingListing('palworld', 'Alt+Num 7', {
    id: 'instant-weapon-cooldown',
    name: 'Instant Weapon Cooldown',
    description: 'Weapon active skills and cooldowns reset instantly',
    category: 'Weapons',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromFlingListing('palworld', 'Alt+Num 8', {
    id: 'infinite-exp',
    name: 'Infinite Exp',
    description: 'Experience gains apply without cap until manually stopped',
    category: 'Stats',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromFlingListing('palworld', 'Alt+Num /', {
    id: 'set-ai-speed',
    name: 'Set AI Speed',
    description: 'Modify Pal and NPC movement/action speed',
    category: 'Game',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 10 },
    tags: ['stepper', 'multiplier'],
  }),
  fromFlingListing('palworld', 'Alt+Num *', {
    id: 'set-movement-speed',
    name: 'Set Movement Speed',
    description: 'Overall locomotion speed including mount traversal',
    category: 'Physics',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.5, max: 10 },
    tags: ['stepper', 'multiplier'],
  }),
  fromFlingListing('palworld', 'Alt+Delete', {
    id: 'infinite-jumps',
    name: 'Infinite Jumps',
    description: 'Jump again before landing',
    category: 'Physics',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromFlingListing('palworld', 'Shift+F1', {
    id: 'edit-max-health',
    name: 'Edit Max Health',
    description: 'Raise or lower maximum player health cap',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1000,
    normalValues: { min: 100, max: 99999 },
    tags: ['stepper'],
  }),
  fromFlingListing('palworld', 'Shift+F2', {
    id: 'edit-max-shield',
    name: 'Edit Max Shield',
    description: 'Raise or lower maximum shield cap',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1000,
    normalValues: { min: 0, max: 99999 },
    tags: ['stepper'],
  }),
  fromFlingListing('palworld', 'Shift+F3', {
    id: 'edit-max-food-cap',
    name: 'Edit Max Food',
    description: 'Raise or lower maximum hunger/food capacity',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 100,
    normalValues: { min: 10, max: 9999 },
    tags: ['stepper'],
  }),
  fromFlingListing('palworld', 'Shift+F4', {
    id: 'edit-max-stamina-cap',
    name: 'Edit Max Stamina',
    description: 'Raise or lower maximum stamina cap',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 500,
    normalValues: { min: 50, max: 99999 },
    tags: ['stepper'],
  }),
  fromFlingListing('palworld', 'Shift+F5', {
    id: 'edit-work-speed',
    name: 'Edit Work Speed',
    description: 'Modify player work speed stat used at bases',
    category: 'Stats',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 20 },
    tags: ['stepper'],
  }),
  fromFlingListing('palworld', 'Shift+F6', {
    id: 'edit-max-weight',
    name: 'Edit Max Weight',
    description: 'Raise or lower carry weight limit',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1000,
    normalValues: { min: 50, max: 999999 },
    tags: ['stepper'],
  }),
];

// ============================================================================
// ATOMFALL (29 cheats)
// ============================================================================

const atomfallCheats: CheatDefinition[] = [
  {
    id: 'infinite-health',
    name: 'Unlimited Health',
    description: 'HP pool never depletes',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityResearch(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'infinite-stamina',
    name: 'Unlimited Stamina',
    description: 'Action points never deplete',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityResearch(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'free-crafting',
    name: 'Free Crafting',
    description: 'Craft items without materials',
    category: 'Game',
    valueType: 'bool',
    requiresDiscovery: true,
    tags: ['toggle', 'bypass'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'unlimited-ammo',
    name: 'Unlimited Ammo',
    description: 'Ammunition never depletes',
    category: 'Weapons',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityResearch(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'undetected',
    name: 'Undetected',
    description: 'Stealth modifier — enemies never notice the player',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'stealth'],
    source: COMMON_SOURCES.communityResearch(),
  }),
  mk({
    id: 'unlimited-crafting-resources',
    name: 'Unlimited Crafting Resources',
    description: 'Crafting materials never deplete',
    category: 'Inventory',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite', 'toggle'],
  }),
  mk({
    id: 'set-skill-points',
    name: 'Set Skill Points',
    description: 'Modify available skill points',
    category: 'Player',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
    source: COMMON_SOURCES.communityResearch(),
  }),
  mk({
    id: 'no-reload-atomfall',
    name: 'No Reload',
    description: 'Remove magazine/reload requirement',
    category: 'Weapons',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'easy-trades',
    name: 'Easy Trades',
    description: 'NPC trade negotiation always succeeds favorably',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'low-heart-rate',
    name: 'Low Heart Rate',
    description: 'Suppresses the heart-rate stealth-detection mechanic',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 0,
    tags: ['toggle', 'stealth'],
    source: COMMON_SOURCES.communityResearch(),
  }),
];

// ============================================================================
// STARDEW VALLEY (50+ console commands)
// ============================================================================

const stardewValleyCheats: CheatDefinition[] = [
  {
    id: 'set-money',
    name: 'Set Money',
    description: 'Modify player currency',
    category: 'Currency',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999999 },
    requiresDiscovery: false,
    tags: ['command', 'currency'],
    source: COMMON_SOURCES.official(),
    verified: true,
    riskLevel: 'safe',
    notes: 'Console command: /money [amount]',
  },
  {
    id: 'add-item',
    name: 'Add Item',
    description: 'Spawn items by ID',
    category: 'Inventory',
    valueType: 'string',
    requiresDiscovery: false,
    tags: ['command', 'inventory'],
    source: COMMON_SOURCES.official(),
    verified: true,
    riskLevel: 'safe',
    notes: 'Console command: /additem [ID] [quantity]',
  },
  {
    id: 'teleport',
    name: 'Teleport to Location',
    description: 'Instantly travel to any location',
    category: 'World',
    valueType: 'string',
    requiresDiscovery: false,
    tags: ['command', 'movement'],
    source: COMMON_SOURCES.official(),
    verified: true,
    riskLevel: 'safe',
    notes: 'Console command: /warp [location] [x] [y]',
  },
  mk({
    id: 'set-max-energy',
    name: 'Set Max Energy',
    description: 'Modify maximum energy pool',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 270,
    normalValues: { min: 0, max: 999 },
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.official(),
    notes: 'Console command: /setmaxenergy [value]',
  }),
  mk({
    id: 'set-health',
    name: 'Set Health',
    description: 'Modify current health',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 100,
    normalValues: { min: 0, max: 999 },
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.official(),
    notes: 'Console command: /sethealth [value]',
  }),
  mk({
    id: 'add-item-by-name',
    name: 'Add Item By Name',
    description: 'Look up and spawn an item by its display name',
    category: 'Inventory',
    valueType: 'string',
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.official(),
    notes: 'Console command: /debug getindex [item name], then /additem',
  }),
  mk({
    id: 'set-friendship',
    name: 'Set Friendship Level',
    description: 'Modify relationship points with a villager',
    category: 'Relationships',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 2500 },
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.smapi(),
    notes: 'CJB Cheats Menu: Relationship Editor',
  }),
  mk({
    id: 'freeze-time',
    name: 'Freeze Time',
    description: 'Stops the in-game clock from advancing',
    category: 'World',
    valueType: 'bool',
    infiniteValue: 1,
    requiresDiscovery: false,
    tags: ['toggle'],
    source: COMMON_SOURCES.smapi(),
    notes: 'CJB Cheats Menu: Time Freezer',
  }),
  mk({
    id: 'set-weather',
    name: 'Set Weather',
    description: 'Force tomorrow’s weather',
    category: 'World',
    valueType: 'string',
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.smapi(),
    notes: 'CJB Cheats Menu: Weather Controller',
  }),
];

// ============================================================================
// AVOWED (45 cheats)
// ============================================================================

const avowedCheats: CheatDefinition[] = [
  // L0 scan-required pins only — no verified AOBs or pointer chains for Avowed yet.
  {
    id: 'infinite-health',
    name: 'Infinite Health',
    description: 'Health resource — L0 scan-required until a verified pointer/AOB exists',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    certLevel: 'L0_Community',
    certificationLevel: 'L0',
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: false,
    riskLevel: 'medium',
    notes: 'L0 / scan_unknown — do not invent UE5 GWorld chains.',
  },
  {
    id: 'infinite-stamina',
    name: 'Infinite Stamina',
    description: 'Stamina resource — L0 scan-required until a verified pointer/AOB exists',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    certLevel: 'L0_Community',
    certificationLevel: 'L0',
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: false,
    riskLevel: 'medium',
    notes: 'L0 / scan_unknown — Steam and WinGDK Game Pass executables share this feature id.',
  },
  {
    id: 'infinite-essence',
    name: 'Infinite Essence',
    description: 'Essence (magic) resource — L0 scan-required until a verified pointer/AOB exists',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    certLevel: 'L0_Community',
    certificationLevel: 'L0',
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: false,
    riskLevel: 'medium',
    notes: 'L0 / scan_unknown — no fabricated AOB or pointer chain.',
  },
  mk({
    id: 'no-fall-damage',
    name: 'No Fall Damage',
    description: 'Falling from any height deals no damage',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'no-weight-avowed',
    name: 'No Weight',
    description: 'Inventory carries no weight penalty',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'unlimited-currency-avowed',
    name: 'Unlimited Currency',
    description: 'Currency never depletes when spending',
    category: 'Inventory',
    valueType: 'int32',
    infiniteValue: 999999,
    tags: ['infinite', 'currency'],
  }),
  mk({
    id: 'set-attribute-points',
    name: 'Set Attribute Points',
    description: 'Modify unspent core attribute points',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-trait-points',
    name: 'Set Trait Points',
    description: 'Modify unspent specialization trait points',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'abilities-no-cooldown',
    name: 'Abilities No Cooldown',
    description: 'All ability cooldowns are removed',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'one-hit-kills',
    name: 'One-Hit Kills',
    description: 'Massively boosts outgoing weapon damage',
    category: 'Weapons',
    valueType: 'float',
    infiniteValue: 9999,
    tags: ['multiplier'],
  }),
];

// ============================================================================
// UNDISPUTED (30 cheats)
// ============================================================================

const undisputedCheats: CheatDefinition[] = [
  {
    id: 'unlimited-health',
    name: 'Unlimited Health',
    description: 'Prevents player knockouts',
    category: 'Player',
    // Undisputed runs on Unreal Engine, which stores continuous stats like health as float,
    // not int (confirmed 2026-07-08: live scanning as int32 converged on a false-positive
    // address that didn't hold under freeze — writes to it had no effect on the actual game).
    // 'toggle' tag still renders this as an Off/On pill in the UI even though the underlying
    // memory value is a float, per resolveMemoryDataType only special-casing 'bool'.
    valueType: 'float',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'infinite-stamina-boxing',
    name: 'Infinite Stamina',
    description: 'Never tire during fights',
    category: 'Player',
    // Same Unreal Engine float reasoning as unlimited-health above.
    valueType: 'float',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'massive-damage',
    name: 'Massive Damage',
    description: 'Boosts outgoing punch damage',
    category: 'Player',
    valueType: 'float',
    infiniteValue: 5,
    normalValues: { min: 1, max: 10 },
    tags: ['multiplier'],
  }),
  mk({
    id: 'player-always-winner',
    name: 'Player Always The Winner',
    description: 'Fight outcome is forced in your favor',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'no-injuries',
    name: '[Career] No Injuries',
    description: 'Boxing injuries are never sustained in career mode',
    category: 'Career',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'set-punch-speed-multiplier',
    name: 'Set Punch Speed Multiplier',
    description: 'Modify punch execution speed',
    category: 'Player',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.5, max: 5 },
    tags: ['stepper', 'multiplier'],
  }),
  // Daze Opponent is a one-shot action in community trainer menus (an "Apply"
  // button, not a toggle) — confirmed 2026-07-08 from reference screenshots.
  // game. Modeled here as tags: ['action'] so the UI renders a single-fire button instead of
  // an Off/On pill; see GameSpecificCheatMenu's isActionCheat().
  mk({
    id: 'daze-opponent',
    name: 'Daze Opponent',
    description: 'Stuns the opponent temporarily',
    category: 'Career',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['action'],
    source: COMMON_SOURCES.communityCatalog(),
  }),
  mk({
    id: 'set-career-money',
    name: '[Career] Set Money',
    description: 'Modify career mode currency',
    category: 'Career',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999999 },
    tags: ['stepper', 'currency'],
  }),
  mk({
    id: 'infinite-cc-stat-points',
    name: '[Career] Infinite CC Stat Points',
    description: 'Character-creation stat points never run out',
    category: 'Career',
    valueType: 'int32',
    infiniteValue: 999,
    tags: ['infinite'],
  }),

  // Stats — exact-value "Set X" career fields, all confirmed present in community trainer references
  // Undisputed menu (2026-07-08 reference screenshot). Each is stepper + apply, same pattern
  // as [Career] Set Money above.
  mk({
    id: 'set-age',
    name: '[Career] Set Age',
    description: "Modify your boxer's age",
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 99 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-weight',
    name: '[Career] Set Weight',
    description: "Modify your boxer's weight",
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-fight-sharpness',
    name: '[Career] Set Fight Sharpness',
    description: 'Modify fight-readiness/sharpness stat',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-energy',
    name: '[Career] Set Energy',
    description: "Modify your boxer's energy stat",
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-fame',
    name: '[Career] Set Fame',
    description: "Modify your boxer's fame stat",
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-money-reward-multiplier',
    name: '[Career] Set Money Reward Multiplier',
    description: 'Modify money earned per fight/event',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-fame-reward-multiplier',
    name: '[Career] Set Fame Reward Multiplier',
    description: 'Modify fame earned per fight/event',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-coach-affinity-reward-multiplier',
    name: '[Career] Set Coach Affinity Reward Multiplier',
    description: 'Modify coach affinity gained per session',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-staff-xp-reward-multiplier',
    name: '[Career] Set Staff XP Reward Multiplier',
    description: 'Modify staff XP gained per session',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-stat-gain-multiplier',
    name: '[Career] Set Stat Gain Multiplier',
    description: 'Modify how fast training increases boxer stats',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),

  // Enemies
  mk({
    id: 'no-stamina-enemy',
    name: 'No Stamina (Enemy)',
    description: 'Opponent stamina depletes rapidly',
    category: 'Enemies',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'easy-to-tire-enemy',
    name: 'Easy to Tire Enemy',
    description: 'Opponent tires much faster than normal',
    category: 'Enemies',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'slowdown-punches',
    name: 'Slowdown Punches',
    description: "Opponent's punches are thrown in slow motion",
    category: 'Enemies',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),

  // Game
  mk({
    id: 'unlimited-round-time',
    name: 'Unlimited Round Time',
    description: 'Round clock never expires',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'easy-knockout-minigame',
    name: 'Easy Knockout Minigame',
    description: 'Simplifies the knockdown recovery minigame',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'all-fight-negotiations-successful',
    name: '[Career] All Fight Negotiations Successful',
    description: 'Contract/fight negotiations always succeed',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'remove-cc-stat-limit',
    name: '[Career] Remove CC Stat Limit',
    description: 'Removes the character-creation stat point cap',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'no-morph-limits',
    name: '[Career] No Morph Limits',
    description: 'Removes character-creation face/body morph slider limits',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'current-slider-min-value',
    name: '[Career] Current Slider Min Value',
    description: 'Sets the minimum bound for the currently selected CC slider',
    category: 'Game',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: -999, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'current-slider-max-value',
    name: '[Career] Current Slider Max Value',
    description: 'Sets the maximum bound for the currently selected CC slider',
    category: 'Game',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: -999, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'current-slider-step-size',
    name: '[Career] Current Slider Step Size',
    description: 'Sets the increment step for the currently selected CC slider',
    category: 'Game',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 100 },
    tags: ['stepper'],
  }),
];

// ============================================================================
// DREDGE (15 cheats — aligned with FLiNG v1.0-v1.5.3+ listing)
// ============================================================================

const dredgeCheats: CheatDefinition[] = [
  {
    id: 'god-mode-dredge',
    name: 'God Mode',
    description: 'Invincibility',
    category: 'Player',
    valueType: 'bool',
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'unlimited-money-dredge',
    name: 'Unlimited Money',
    description: 'Currency modifier',
    category: 'Currency',
    valueType: 'int32',
    infiniteValue: 999999,
    requiresDiscovery: true,
    tags: ['infinite', 'currency'],
    source: COMMON_SOURCES.communityCatalog(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'instant-harvest',
    name: 'Instant Harvest',
    description: 'Fishing minigames resolve immediately with success',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'fish-wont-spoil',
    name: "Fish Won't Spoil",
    description: 'Caught fish never degrade in the hold',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'fish-wont-be-infected',
    name: "Fish Won't Be Infected",
    description: 'Immunity to the corruption/infection mechanic',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'unlimited-nets-durability',
    name: 'Unlimited Nets Durability',
    description: 'Fishing nets never wear out',
    category: 'Boat',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite'],
  }),
  mk({
    id: 'unlimited-pots-durability',
    name: 'Unlimited Pots Durability',
    description: 'Crab pots never wear out',
    category: 'Boat',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite'],
  }),
  mk({
    id: 'ignore-upgrade-requirements',
    name: 'Ignore Upgrade Requirements',
    description: 'Ship upgrades apply without materials',
    category: 'Boat',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'bypass'],
  }),
  mk({
    id: 'set-boat-speed',
    name: 'Set Boat Speed',
    description: 'Modify vessel movement speed',
    category: 'Boat',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.5, max: 5 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'item-sell-price-multiplier',
    name: 'Item Sell Price Multiplier',
    description: 'Modify how much sold catches are worth',
    category: 'Currency',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 1, max: 10 },
    tags: ['stepper', 'multiplier'],
  }),
  fromFlingListing('dredge', 'Num 4', {
    id: 'ignore-equipment-requirements',
    name: 'Ignore Equipment Requirements',
    description: 'Equip gear without meeting level or material prerequisites',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'bypass'],
  }),
  fromFlingListing('dredge', 'Num 0', {
    id: 'infinite-research-parts',
    name: 'Infinite Research Parts',
    description: 'Research currency never depletes',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite'],
  }),
  fromFlingListing('dredge', 'Ctrl+Num 1', {
    id: 'set-movement-speed-dredge',
    name: 'Set Movement Speed',
    description: 'Modify on-foot movement speed on the boat and docks',
    category: 'Player',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.5, max: 5 },
    tags: ['stepper', 'multiplier'],
  }),
  fromFlingListing('dredge', 'Ctrl+Num 2', {
    id: 'set-game-speed-dredge',
    name: 'Set Game Speed',
    description: 'Global simulation speed multiplier',
    category: 'Game',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 5 },
    tags: ['stepper', 'time'],
  }),
  fromFlingListing('dredge', 'Ctrl+Num 3', {
    id: 'freeze-time-dredge',
    name: 'Freeze Time',
    description: 'Stop the in-game clock from advancing',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'time'],
  }),
  fromFlingListing('dredge', 'Ctrl+Num 4', {
    id: 'time-pass-speed-dredge',
    name: 'Time Pass Speed',
    description: 'Adjust how quickly days and nights advance',
    category: 'Game',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0, max: 20 },
    tags: ['stepper', 'time'],
  }),
];

// ============================================================================
// CRIMSON DESERT (23 cheats — from community CrimsonDesert.CT metadata)
// ============================================================================

const crimsonDesertCheats: CheatDefinition[] = [
  fromCommunityCt({
    id: 'auto-fill-hp-sta-spi-cd',
    name: 'Auto Fill HP/Sta/Spi',
    description: 'Keeps health, stamina, and spirit topped when addresses are resolved',
    category: 'Player',
    valueType: 'float',
    infiniteValue: 9999,
    tags: ['infinite', 'toggle'],
  }),
  fromCommunityCt({
    id: 'fast-enemy-kill-cd',
    name: 'Fast Enemy Kill / Char HP Full',
    description: 'Eliminates enemies quickly or maintains full player health',
    category: 'Enemies',
    valueType: 'float',
    infiniteValue: 9999,
    tags: ['multiplier'],
  }),
  fromCommunityCt({
    id: 'ez-parry-cd',
    name: 'Easy Parry',
    description: 'Expands parry timing window',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromCommunityCt({
    id: 'blink-spell-cd',
    name: 'Blink Spell',
    description: 'Short-range teleport spell assist',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromCommunityCt({
    id: 'set-attack-defense-cd',
    name: 'Set Attack/Defense',
    description: 'Modify outgoing attack and damage reduction',
    category: 'Stats',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 50 },
    tags: ['stepper'],
  }),
  fromCommunityCt({
    id: 'get-resistant-attrs-cd',
    name: 'Get Resistant Attributes',
    description: 'Inspect or modify elemental resistances',
    category: 'Stats',
    valueType: 'float',
    tags: ['stepper'],
  }),
  fromCommunityCt({
    id: 'infinite-weapon-polish-cd',
    name: 'Infinite Weapon Polishing Durability',
    description: 'Weapon polish meter does not deplete',
    category: 'Weapons',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite'],
  }),
  fromCommunityCt({
    id: 'set-max-bag-size-cd',
    name: 'Set Max Bag Size',
    description: 'Raise inventory capacity cap',
    category: 'Inventory',
    valueType: 'int32',
    defaultValue: 999,
    normalValues: { min: 50, max: 9999 },
    tags: ['stepper'],
  }),
  fromCommunityCt({
    id: 'fixed-item-amounts-cd',
    name: 'Fixed Item Amounts (Ammo/Copper/Materials)',
    description: 'Maintains configured minimum stacks for common resources',
    category: 'Inventory',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite'],
  }),
  fromCommunityCt({
    id: 'vendor-buyback-list-cd',
    name: 'Get Vendor Buyback Item List',
    description: 'Surface vendor buyback inventory entries',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromCommunityCt({
    id: 'item-decrease-guard-cd',
    name: 'Item Decrease Guard',
    description: 'Prevent item counts from dropping inside a defined range',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromCommunityCt({
    id: 'menu-set-item-amount-cd',
    name: 'Menu: Set Item Amount on Add',
    description: 'Forces stack size when adding items from menus',
    category: 'Inventory',
    valueType: 'int32',
    defaultValue: 99,
    normalValues: { min: 1, max: 9999 },
    tags: ['stepper'],
  }),
  fromCommunityCt({
    id: 'abyss-gear-cd',
    name: 'Abyss Gear',
    description: 'Abyss equipment related tweaks',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromCommunityCt({
    id: 'browse-kuku-item-cd',
    name: 'Browse Kuku / Item Addresses',
    description: 'Item browser helper from community table',
    category: 'Research',
    valueType: 'int64',
    tags: ['discovery'],
  }),
  fromCommunityCt({
    id: 'open-item-id-gui-cd',
    name: 'Open Item ID Query GUI',
    description: 'Lookup item IDs from the community script GUI',
    category: 'Research',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['discovery'],
  }),
  fromCommunityCt({
    id: 'fast-friendship-cd',
    name: 'Fast Friendship',
    description: 'Accelerates NPC relationship gains',
    category: 'Game',
    valueType: 'float',
    defaultValue: 5.0,
    normalValues: { min: 1, max: 20 },
    tags: ['multiplier'],
  }),
  fromCommunityCt({
    id: 'fast-pet-friendship-cd',
    name: 'Fast Pet Friendship and Take',
    description: 'Speeds up pet bonding and pickup interactions',
    category: 'Game',
    valueType: 'float',
    defaultValue: 5.0,
    normalValues: { min: 1, max: 20 },
    tags: ['multiplier'],
  }),
  fromCommunityCt({
    id: 'archery-competition-cd',
    name: 'Archery Competition Data',
    description: 'Read or tweak archery minigame values',
    category: 'Game',
    valueType: 'float',
    tags: ['stepper'],
  }),
  fromCommunityCt({
    id: 'fast-dragon-cooldown-cd',
    name: 'Fast Dragon Cooldown',
    description: 'Reduces dragon mount/skill cooldown timers',
    category: 'Game',
    valueType: 'float',
    defaultValue: 0.1,
    normalValues: { min: 0, max: 1 },
    tags: ['multiplier'],
  }),
  fromCommunityCt({
    id: 'reputation-no-decrease-cd',
    name: 'Reputation No Decrease',
    description: 'Locks reputation from falling',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  fromCommunityCt({
    id: 'get-hp-aob-cd',
    name: 'Get HP Address (AOB Mode)',
    description: 'Discovery helper for health address via AOB scan',
    category: 'Research',
    valueType: 'float',
    tags: ['discovery'],
  }),
  fromCommunityCt({
    id: 'get-char-pointer-cd',
    name: 'Get Current Character Pointer',
    description: 'Resolves the active character base pointer',
    category: 'Research',
    valueType: 'int64',
    tags: ['discovery'],
  }),
  fromCommunityCt({
    id: 'freeze-daytime-cd',
    name: 'Freeze Daytime',
    description: 'Stops the in-game clock',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
];

// ============================================================================
// GAME CONFIGURATIONS
// ============================================================================

export const PALWORLD_CONFIG: GameConfig = {
  gameId: 'palworld',
  name: 'Palworld',
  executable: 'Palworld-Win64-Shipping.exe',
  aliases: ['Palworld.exe'],
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'stats', name: 'Stats' },
    { id: 'weapons', name: 'Weapons' },
    { id: 'enemies', name: 'Enemies' },
    { id: 'game', name: 'Game' },
    { id: 'physics', name: 'Physics' },
  ],
  cheats: palworldCheats,
  connectionBaseline: 4,
  description:
    'Monster taming and crafting game. Memory cheats are solo/offline only (community trainers list 48 options for v1.0+).',
  releaseDate: '2024-01-19',
  lastUpdated: new Date('2026-07-13'),
  images: steamImages(1623730),
  pinnedCheatIds: ['infinite-player-health', 'infinite-stamina', 'instant-capture'],
};

export const ATOMFALL_CONFIG: GameConfig = {
  gameId: 'atomfall',
  name: 'Atomfall',
  executable: 'Atomfall.exe',
  aliases: ['Atomfall_dx12.exe'],
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'weapons', name: 'Weapons' },
    { id: 'game', name: 'Game' },
  ],
  cheats: atomfallCheats,
  connectionBaseline: 2,
  description: 'Post-apocalyptic action-adventure with Xbox Live integration',
  lastUpdated: new Date('2026-07-08'),
  images: steamImages(2075450),
  pinnedCheatIds: ['infinite-health', 'infinite-stamina', 'free-crafting'],
};

export const STARDEW_VALLEY_CONFIG: GameConfig = {
  gameId: 'stardew-valley',
  name: 'Stardew Valley',
  executable: 'StardewValley.exe',
  aliases: ['Stardew Valley.exe'],
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'console-command',
  dataType: 'int32',
  categories: [
    { id: 'currency', name: 'Currency' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'stats', name: 'Stats' },
    { id: 'relationships', name: 'Relationships' },
    { id: 'world', name: 'World' },
  ],
  cheats: stardewValleyCheats,
  connectionBaseline: 5,
  description: 'Farming simulation with built-in console commands (1.6.0+)',
  lastUpdated: new Date('2026-07-08'),
  images: steamImages(413150),
  pinnedCheatIds: ['set-money', 'teleport'],
};

export const AVOWED_CONFIG: GameConfig = {
  gameId: 'avowed',
  name: 'Avowed',
  executable: 'Avowed.exe',
  // Xbox PC Game Pass / WinGDK shipping binary (alongside Steam Avowed.exe).
  aliases: ['Avowed-WinGDK-Shipping.exe'],
  platform: 'xbox-game-pass',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'stats', name: 'Stats' },
    { id: 'weapons', name: 'Weapons' },
  ],
  cheats: avowedCheats,
  connectionBaseline: 0,
  description:
    'Obsidian RPG — L0 scan-required memory features only (Steam + Xbox PC Game Pass WinGDK). No verified AOBs yet.',
  lastUpdated: new Date('2026-07-18'),
  images: steamImages(2457220),
  pinnedCheatIds: ['infinite-health', 'infinite-stamina', 'infinite-essence'],
};

export const UNDISPUTED_CONFIG: GameConfig = {
  gameId: 'undisputed',
  name: 'Undisputed',
  executable: 'Undisputed.exe',
  // Confirmed live: process path is under WindowsApps\DeepSilver.Undisputed_* — Microsoft
  // Store/Xbox packaging, not Steam.
  platform: 'xbox-game-pass',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'career', name: 'Career' },
    { id: 'stats', name: 'Stats' },
    { id: 'enemies', name: 'Enemies' },
    { id: 'game', name: 'Game' },
  ],
  cheats: undisputedCheats,
  connectionBaseline: 7, // Measured 2026-07-08 during offline tutorial — see game-connection-baselines.ts
  description: 'Boxing simulation with stat and career mode cheats',
  lastUpdated: new Date('2026-07-08'),
  images: steamImages(1148810), // Steam art used for header/icon even for the Game Pass build — cosmetic only
  pinnedCheatIds: ['unlimited-health', 'infinite-stamina-boxing'],
};

export const DREDGE_CONFIG: GameConfig = {
  gameId: 'dredge',
  name: 'Dredge',
  executable: 'Dredge.exe',
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'currency', name: 'Currency' },
    { id: 'boat', name: 'Boat' },
  ],
  cheats: dredgeCheats,
  connectionBaseline: 0,
  description: 'Indie horror fishing game with 15 community-listed progression cheats (FLiNG v1.0-v1.5.3+).',
  lastUpdated: new Date('2026-07-13'),
  images: steamImages(1562430),
  pinnedCheatIds: ['god-mode-dredge', 'unlimited-money-dredge'],
};

export const CRIMSON_DESERT_CONFIG: GameConfig = {
  gameId: 'crimson-desert',
  name: 'Crimson Desert',
  executable: 'CrimsonDesert.exe',
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'stats', name: 'Stats' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'weapons', name: 'Weapons' },
    { id: 'enemies', name: 'Enemies' },
    { id: 'game', name: 'Game' },
    { id: 'research', name: 'Research' },
  ],
  cheats: crimsonDesertCheats,
  connectionBaseline: 0,
  description:
    'Pearl Abyss action-adventure — 23 cheats from community CrimsonDesert.CT (OpenCheatTables, Auto Assembler reference).',
  lastUpdated: new Date('2026-07-13'),
  pinnedCheatIds: ['auto-fill-hp-sta-spi-cd', 'fast-enemy-kill-cd', 'set-attack-defense-cd'],
};

// ============================================================================
// REGISTRY EXPORTS
// ============================================================================

/**
 * Phase 4 — presentation registry only. Capability SoT is schema.v1.
 * Do not extend with new titles for execute/live/save authority.
 */
export const ALL_GAMES = [
  PALWORLD_CONFIG,
  ATOMFALL_CONFIG,
  STARDEW_VALLEY_CONFIG,
  AVOWED_CONFIG,
  UNDISPUTED_CONFIG,
  DREDGE_CONFIG,
  CRIMSON_DESERT_CONFIG,
];
