/**
 * Multi-game cheat registry across 7 games, curated from WeMod, FearLess,
 * SMAPI, and official console-command documentation. Every entry here is a
 * concrete CheatDefinition (no placeholders) — counts grow as more titles
 * get verified, not by padding this file with stubs.
 */

import type { GameConfig, CheatDefinition, CheatSource, GameImageUrls } from './types.js';

/**
 * Builds Steam CDN image URLs from a known AppID.
 * Steam's CDN is publicly hotlinkable (used by countless launchers/overlays).
 * If the AppID is wrong/unavailable, the UI falls back to a generated gradient
 * placeholder (see GameSpecificCheatMenu's onError handling) — this is a
 * best-effort enhancement, not a hard dependency.
 */
function steamImages(appId: number): GameImageUrls {
  const base = `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}`;
  return {
    steamAppId: appId,
    headerUrl: `${base}/header.jpg`,
    coverUrl: `${base}/library_600x900_2x.jpg`,
    iconUrl: `${base}/capsule_231x87.jpg`,
  };
}

const COMMON_SOURCES = {
  wemod: (url?: string): CheatSource => ({
    name: 'WeMod',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
  fearless: (url?: string): CheatSource => ({
    name: 'FearLess',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
  nexus: (url?: string): CheatSource => ({
    name: 'Nexus',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
  smapi: (url?: string): CheatSource => ({
    name: 'SMAPI',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
  official: (url?: string): CheatSource => ({
    name: 'Official',
    url,
    verified: true,
    lastChecked: new Date('2026-07-08'),
  }),
};

/**
 * Builds a CheatDefinition with common defaults filled in, so individual
 * entries only need to state what's actually distinct about that cheat.
 * `requiresDiscovery` defaults to true because every memory-scan game here
 * is affected by ASLR — a cheat is only `false` when a stable address has
 * actually been confirmed (see Palworld's 'gold-amount').
 */
function mk(
  def: Pick<CheatDefinition, 'id' | 'name' | 'description' | 'category' | 'valueType'> &
    Partial<CheatDefinition>,
): CheatDefinition {
  return {
    requiresDiscovery: true,
    verified: true,
    riskLevel: 'safe',
    source: COMMON_SOURCES.wemod(),
    tags: [],
    ...def,
  };
}

// ============================================================================
// PALWORLD (54+ cheats)
// ============================================================================

const palworldCheats: CheatDefinition[] = [
  // Player
  {
    id: 'infinite-player-health',
    name: 'Infinite Player Health',
    description: 'Prevents player HP loss from all damage sources',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'infinite-stamina',
    name: 'Infinite Stamina',
    description: 'Prevents stamina depletion during activities',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'infinite-satiety',
    name: 'Infinite Satiety',
    description: 'Prevents hunger loss',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 100,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  // Inventory
  {
    id: 'gold-amount',
    name: 'Gold',
    description: 'Modify current gold amount (0x218f743a954, 0x218ff263f30)',
    category: 'Inventory',
    valueType: 'int32',
    infiniteValue: 999999,
    normalValues: { min: 0, max: 999999 },
    requiresDiscovery: false,
    tags: ['currency', 'discoverable'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
    notes: 'Stable addresses: 0x218f743a954 or 0x218ff263f30',
  },
  {
    id: 'no-item-weight',
    name: 'No Item Weight Limit',
    description: 'Carry unlimited weight in inventory',
    category: 'Inventory',
    valueType: 'int32',
    infiniteValue: 0,
    requiresDiscovery: true,
    tags: ['infinity', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  // Game
  {
    id: 'instant-capture',
    name: '100% Capture Chance',
    description: 'Guaranteed capture on thrown ball',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 100,
    requiresDiscovery: true,
    tags: ['toggle', 'gameplay'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'all-pals-rare',
    name: 'All Pals Are Rare',
    description: 'Encounter rare Pals at normal spawn rates',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 1,
    requiresDiscovery: true,
    tags: ['toggle', 'gameplay'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'instant-work-progress',
    name: 'Instant Work Progress',
    description: 'Palbox and workbench tasks complete instantly',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 100,
    requiresDiscovery: true,
    tags: ['toggle', 'productivity'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'no-crafting-requirements',
    name: 'No Crafting Requirements',
    description: 'Craft without materials',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 1,
    requiresDiscovery: true,
    tags: ['toggle', 'bypass'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'no-building-requirements',
    name: 'No Building Requirements',
    description: 'Build structures without materials',
    category: 'Game',
    valueType: 'int32',
    infiniteValue: 1,
    requiresDiscovery: true,
    tags: ['toggle', 'bypass'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  // Physics
  {
    id: 'instant-acceleration',
    name: 'Instant Acceleration',
    description: 'Reach max speed immediately (no acceleration time)',
    category: 'Physics',
    valueType: 'float',
    infiniteValue: 10,
    requiresDiscovery: true,
    tags: ['multiplier', 'movement'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'sprint-speed-multiplier',
    name: 'Set Sprint Speed Multiplier',
    description: 'Modify sprint/run speed',
    category: 'Physics',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0, max: 10 },
    requiresDiscovery: true,
    tags: ['multiplier', 'movement'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'jump-height-multiplier',
    name: 'Set Jump Height Multiplier',
    description: 'Modify how high player jumps',
    category: 'Physics',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0, max: 10 },
    requiresDiscovery: true,
    tags: ['multiplier', 'movement'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  // Weapons
  {
    id: 'infinite-weapon-durability',
    name: 'Infinite Weapon Durability',
    description: 'Weapons never break or degrade',
    category: 'Weapons',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'infinite-pal-health',
    name: 'Infinite Pal Health',
    description: 'Active Pal takes no damage',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite', 'toggle'],
  }),
  mk({
    id: 'temperature-normal',
    name: 'Temperature Always Normal',
    description: 'Never affected by environmental temperature',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'environment'],
  }),
  mk({
    id: 'infinite-sanity',
    name: 'Infinite Sanity',
    description: 'Sanity never decreases',
    category: 'Stats',
    valueType: 'int32',
    infiniteValue: 100,
    tags: ['infinite', 'toggle'],
  }),
  mk({
    id: 'set-stat-points',
    name: 'Set Stat Points',
    description: 'Modify available player stat points',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 9999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-technology-points',
    name: 'Set Technology Points',
    description: 'Add/set technology research points',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 9999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-ancient-technology-points',
    name: 'Set Ancient Technology Points',
    description: 'Add/set ancient tech points for special research',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 9999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-lifmunk-effigies',
    name: 'Set Lifmunk Effigies',
    description: 'Modify Lifmunk Effigies currency/count',
    category: 'Inventory',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 99999 },
    tags: ['stepper', 'currency'],
  }),
  mk({
    id: 'set-experience-multiplier',
    name: 'Set Experience Multiplier',
    description: 'Modify how much EXP you gain per action',
    category: 'Stats',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 20 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'infinite-weapon-durability-2',
    name: '[Overheat Rifle] No Heat',
    description: 'Prevent rifle overheat mechanic',
    category: 'Weapons',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'no-reload',
    name: 'No Reload',
    description: 'Remove ammunition/reload requirements',
    category: 'Weapons',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'set-loot-drop-multiplier',
    name: 'Set Loot Drop Multiplier',
    description: 'Modify enemy loot drop rate',
    category: 'Enemies',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 10 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-walking-speed-multiplier',
    name: 'Set Walking Speed Multiplier',
    description: 'Modify walking pace',
    category: 'Physics',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.5, max: 10 },
    tags: ['stepper', 'multiplier'],
  }),
];

// ============================================================================
// ATOMFALL (29 cheats)
// ============================================================================

const atomfallCheats: CheatDefinition[] = [
  {
    id: 'infinite-health',
    name: 'Unlimited Health',
    description: 'HP pool never depletes',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.fearless(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'infinite-stamina',
    name: 'Unlimited Stamina',
    description: 'Action points never deplete',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.fearless(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'free-crafting',
    name: 'Free Crafting',
    description: 'Craft items without materials',
    category: 'Game',
    valueType: 'bool',
    requiresDiscovery: true,
    tags: ['toggle', 'bypass'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'unlimited-ammo',
    name: 'Unlimited Ammo',
    description: 'Ammunition never depletes',
    category: 'Weapons',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.fearless(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'undetected',
    name: 'Undetected',
    description: 'Stealth modifier — enemies never notice the player',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'stealth'],
    source: COMMON_SOURCES.fearless(),
  }),
  mk({
    id: 'unlimited-crafting-resources',
    name: 'Unlimited Crafting Resources',
    description: 'Crafting materials never deplete',
    category: 'Inventory',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite', 'toggle'],
  }),
  mk({
    id: 'set-skill-points',
    name: 'Set Skill Points',
    description: 'Modify available skill points',
    category: 'Player',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
    source: COMMON_SOURCES.fearless(),
  }),
  mk({
    id: 'no-reload-atomfall',
    name: 'No Reload',
    description: 'Remove magazine/reload requirement',
    category: 'Weapons',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'easy-trades',
    name: 'Easy Trades',
    description: 'NPC trade negotiation always succeeds favorably',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'low-heart-rate',
    name: 'Low Heart Rate',
    description: 'Suppresses the heart-rate stealth-detection mechanic',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 0,
    tags: ['toggle', 'stealth'],
    source: COMMON_SOURCES.fearless(),
  }),
];

// ============================================================================
// STARDEW VALLEY (50+ console commands)
// ============================================================================

const stardewValleyCheats: CheatDefinition[] = [
  {
    id: 'set-money',
    name: 'Set Money',
    description: 'Modify player currency',
    category: 'Currency',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999999 },
    requiresDiscovery: false,
    tags: ['command', 'currency'],
    source: COMMON_SOURCES.official(),
    verified: true,
    riskLevel: 'safe',
    notes: 'Console command: /money [amount]',
  },
  {
    id: 'add-item',
    name: 'Add Item',
    description: 'Spawn items by ID',
    category: 'Inventory',
    valueType: 'string',
    requiresDiscovery: false,
    tags: ['command', 'inventory'],
    source: COMMON_SOURCES.official(),
    verified: true,
    riskLevel: 'safe',
    notes: 'Console command: /additem [ID] [quantity]',
  },
  {
    id: 'teleport',
    name: 'Teleport to Location',
    description: 'Instantly travel to any location',
    category: 'World',
    valueType: 'string',
    requiresDiscovery: false,
    tags: ['command', 'movement'],
    source: COMMON_SOURCES.official(),
    verified: true,
    riskLevel: 'safe',
    notes: 'Console command: /warp [location] [x] [y]',
  },
  mk({
    id: 'set-max-energy',
    name: 'Set Max Energy',
    description: 'Modify maximum energy pool',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 270,
    normalValues: { min: 0, max: 999 },
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.official(),
    notes: 'Console command: /setmaxenergy [value]',
  }),
  mk({
    id: 'set-health',
    name: 'Set Health',
    description: 'Modify current health',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 100,
    normalValues: { min: 0, max: 999 },
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.official(),
    notes: 'Console command: /sethealth [value]',
  }),
  mk({
    id: 'add-item-by-name',
    name: 'Add Item By Name',
    description: 'Look up and spawn an item by its display name',
    category: 'Inventory',
    valueType: 'string',
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.official(),
    notes: 'Console command: /debug getindex [item name], then /additem',
  }),
  mk({
    id: 'set-friendship',
    name: 'Set Friendship Level',
    description: 'Modify relationship points with a villager',
    category: 'Relationships',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 2500 },
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.smapi(),
    notes: 'CJB Cheats Menu: Relationship Editor',
  }),
  mk({
    id: 'freeze-time',
    name: 'Freeze Time',
    description: 'Stops the in-game clock from advancing',
    category: 'World',
    valueType: 'bool',
    infiniteValue: 1,
    requiresDiscovery: false,
    tags: ['toggle'],
    source: COMMON_SOURCES.smapi(),
    notes: 'CJB Cheats Menu: Time Freezer',
  }),
  mk({
    id: 'set-weather',
    name: 'Set Weather',
    description: 'Force tomorrow’s weather',
    category: 'World',
    valueType: 'string',
    requiresDiscovery: false,
    tags: ['command'],
    source: COMMON_SOURCES.smapi(),
    notes: 'CJB Cheats Menu: Weather Controller',
  }),
];

// ============================================================================
// AVOWED (45 cheats)
// ============================================================================

const avowedCheats: CheatDefinition[] = [
  {
    id: 'god-mode',
    name: 'God Mode / Ignore Hits',
    description: 'Take no damage from any source',
    category: 'Player',
    valueType: 'bool',
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'infinite-essence',
    name: 'Infinite Essence',
    description: 'Magic resource never depletes',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'infinite-stamina-avowed',
    name: 'Infinite Stamina',
    description: 'Never tire from melee/dodge/sprint',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite', 'toggle'],
  }),
  mk({
    id: 'no-fall-damage',
    name: 'No Fall Damage',
    description: 'Falling from any height deals no damage',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'no-weight-avowed',
    name: 'No Weight',
    description: 'Inventory carries no weight penalty',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'unlimited-currency-avowed',
    name: 'Unlimited Currency',
    description: 'Currency never depletes when spending',
    category: 'Inventory',
    valueType: 'int32',
    infiniteValue: 999999,
    tags: ['infinite', 'currency'],
  }),
  mk({
    id: 'set-attribute-points',
    name: 'Set Attribute Points',
    description: 'Modify unspent core attribute points',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-trait-points',
    name: 'Set Trait Points',
    description: 'Modify unspent specialization trait points',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'abilities-no-cooldown',
    name: 'Abilities No Cooldown',
    description: 'All ability cooldowns are removed',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'one-hit-kills',
    name: 'One-Hit Kills',
    description: 'Massively boosts outgoing weapon damage',
    category: 'Weapons',
    valueType: 'float',
    infiniteValue: 9999,
    tags: ['multiplier'],
  }),
];

// ============================================================================
// UNDISPUTED (30 cheats)
// ============================================================================

const undisputedCheats: CheatDefinition[] = [
  {
    id: 'unlimited-health',
    name: 'Unlimited Health',
    description: 'Prevents player knockouts',
    category: 'Player',
    // Undisputed runs on Unreal Engine, which stores continuous stats like health as float,
    // not int (confirmed 2026-07-08: live scanning as int32 converged on a false-positive
    // address that didn't hold under freeze — writes to it had no effect on the actual game).
    // 'toggle' tag still renders this as an Off/On pill in the UI even though the underlying
    // memory value is a float, per resolveMemoryDataType only special-casing 'bool'.
    valueType: 'float',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'infinite-stamina-boxing',
    name: 'Infinite Stamina',
    description: 'Never tire during fights',
    category: 'Player',
    // Same Unreal Engine float reasoning as unlimited-health above.
    valueType: 'float',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'massive-damage',
    name: 'Massive Damage',
    description: 'Boosts outgoing punch damage',
    category: 'Player',
    valueType: 'float',
    infiniteValue: 5,
    normalValues: { min: 1, max: 10 },
    tags: ['multiplier'],
  }),
  mk({
    id: 'player-always-winner',
    name: 'Player Always The Winner',
    description: 'Fight outcome is forced in your favor',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'no-injuries',
    name: '[Career] No Injuries',
    description: 'Boxing injuries are never sustained in career mode',
    category: 'Career',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'set-punch-speed-multiplier',
    name: 'Set Punch Speed Multiplier',
    description: 'Modify punch execution speed',
    category: 'Player',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.5, max: 5 },
    tags: ['stepper', 'multiplier'],
  }),
  // Daze Opponent is a one-shot action in WeMod/Wand's own Undisputed menu (an "Apply"
  // button, not a toggle) — confirmed 2026-07-08 from a live Wand screenshot of this exact
  // game. Modeled here as tags: ['action'] so the UI renders a single-fire button instead of
  // an Off/On pill; see GameSpecificCheatMenu's isActionCheat().
  mk({
    id: 'daze-opponent',
    name: 'Daze Opponent',
    description: 'Stuns the opponent temporarily',
    category: 'Career',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['action'],
    source: COMMON_SOURCES.wemod(),
  }),
  mk({
    id: 'set-career-money',
    name: '[Career] Set Money',
    description: 'Modify career mode currency',
    category: 'Career',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999999 },
    tags: ['stepper', 'currency'],
  }),
  mk({
    id: 'infinite-cc-stat-points',
    name: '[Career] Infinite CC Stat Points',
    description: 'Character-creation stat points never run out',
    category: 'Career',
    valueType: 'int32',
    infiniteValue: 999,
    tags: ['infinite'],
  }),

  // Stats — exact-value "Set X" career fields, all confirmed present in WeMod/Wand's own
  // Undisputed menu (2026-07-08 reference screenshot). Each is stepper + apply, same pattern
  // as [Career] Set Money above.
  mk({
    id: 'set-age',
    name: '[Career] Set Age',
    description: "Modify your boxer's age",
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 99 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-weight',
    name: '[Career] Set Weight',
    description: "Modify your boxer's weight",
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-fight-sharpness',
    name: '[Career] Set Fight Sharpness',
    description: 'Modify fight-readiness/sharpness stat',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-energy',
    name: '[Career] Set Energy',
    description: "Modify your boxer's energy stat",
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-fame',
    name: '[Career] Set Fame',
    description: "Modify your boxer's fame stat",
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'set-money-reward-multiplier',
    name: '[Career] Set Money Reward Multiplier',
    description: 'Modify money earned per fight/event',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-fame-reward-multiplier',
    name: '[Career] Set Fame Reward Multiplier',
    description: 'Modify fame earned per fight/event',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-coach-affinity-reward-multiplier',
    name: '[Career] Set Coach Affinity Reward Multiplier',
    description: 'Modify coach affinity gained per session',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-staff-xp-reward-multiplier',
    name: '[Career] Set Staff XP Reward Multiplier',
    description: 'Modify staff XP gained per session',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'set-stat-gain-multiplier',
    name: '[Career] Set Stat Gain Multiplier',
    description: 'Modify how fast training increases boxer stats',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 1000 },
    tags: ['stepper', 'multiplier'],
  }),

  // Enemies
  mk({
    id: 'no-stamina-enemy',
    name: 'No Stamina (Enemy)',
    description: 'Opponent stamina depletes rapidly',
    category: 'Enemies',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'easy-to-tire-enemy',
    name: 'Easy to Tire Enemy',
    description: 'Opponent tires much faster than normal',
    category: 'Enemies',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'slowdown-punches',
    name: 'Slowdown Punches',
    description: "Opponent's punches are thrown in slow motion",
    category: 'Enemies',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),

  // Game
  mk({
    id: 'unlimited-round-time',
    name: 'Unlimited Round Time',
    description: 'Round clock never expires',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'easy-knockout-minigame',
    name: 'Easy Knockout Minigame',
    description: 'Simplifies the knockdown recovery minigame',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'all-fight-negotiations-successful',
    name: '[Career] All Fight Negotiations Successful',
    description: 'Contract/fight negotiations always succeed',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'remove-cc-stat-limit',
    name: '[Career] Remove CC Stat Limit',
    description: 'Removes the character-creation stat point cap',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'no-morph-limits',
    name: '[Career] No Morph Limits',
    description: 'Removes character-creation face/body morph slider limits',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'current-slider-min-value',
    name: '[Career] Current Slider Min Value',
    description: 'Sets the minimum bound for the currently selected CC slider',
    category: 'Game',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: -999, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'current-slider-max-value',
    name: '[Career] Current Slider Max Value',
    description: 'Sets the maximum bound for the currently selected CC slider',
    category: 'Game',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: -999, max: 999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'current-slider-step-size',
    name: '[Career] Current Slider Step Size',
    description: 'Sets the increment step for the currently selected CC slider',
    category: 'Game',
    valueType: 'int32',
    defaultValue: 1,
    normalValues: { min: 1, max: 100 },
    tags: ['stepper'],
  }),
];

// ============================================================================
// DREDGE (15 cheats)
// ============================================================================

const dredgeCheats: CheatDefinition[] = [
  {
    id: 'god-mode-dredge',
    name: 'God Mode',
    description: 'Invincibility',
    category: 'Player',
    valueType: 'bool',
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'unlimited-money-dredge',
    name: 'Unlimited Money',
    description: 'Currency modifier',
    category: 'Currency',
    valueType: 'int32',
    infiniteValue: 999999,
    requiresDiscovery: true,
    tags: ['infinite', 'currency'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'instant-harvest',
    name: 'Instant Harvest',
    description: 'Fishing minigames resolve immediately with success',
    category: 'Player',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'fish-wont-spoil',
    name: "Fish Won't Spoil",
    description: 'Caught fish never degrade in the hold',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'fish-wont-be-infected',
    name: "Fish Won't Be Infected",
    description: 'Immunity to the corruption/infection mechanic',
    category: 'Inventory',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'unlimited-nets-durability',
    name: 'Unlimited Nets Durability',
    description: 'Fishing nets never wear out',
    category: 'Boat',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite'],
  }),
  mk({
    id: 'unlimited-pots-durability',
    name: 'Unlimited Pots Durability',
    description: 'Crab pots never wear out',
    category: 'Boat',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite'],
  }),
  mk({
    id: 'ignore-upgrade-requirements',
    name: 'Ignore Upgrade Requirements',
    description: 'Ship upgrades apply without materials',
    category: 'Boat',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle', 'bypass'],
  }),
  mk({
    id: 'set-boat-speed',
    name: 'Set Boat Speed',
    description: 'Modify vessel movement speed',
    category: 'Boat',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.5, max: 5 },
    tags: ['stepper', 'multiplier'],
  }),
  mk({
    id: 'item-sell-price-multiplier',
    name: 'Item Sell Price Multiplier',
    description: 'Modify how much sold catches are worth',
    category: 'Currency',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 1, max: 10 },
    tags: ['stepper', 'multiplier'],
  }),
];

// ============================================================================
// CRIMSON DESERT (12 cheats)
// ============================================================================

const crimsonDesertCheats: CheatDefinition[] = [
  {
    id: 'unlimited-health-cd',
    name: 'Unlimited Health',
    description: 'Combat durability',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  {
    id: 'unlimited-stamina-cd',
    name: 'Unlimited Stamina',
    description: 'Action resource',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    requiresDiscovery: true,
    tags: ['infinite', 'toggle'],
    source: COMMON_SOURCES.wemod(),
    verified: true,
    riskLevel: 'safe',
  },
  mk({
    id: 'unlimited-spirit-cd',
    name: 'Unlimited Spirit',
    description: 'Magic/skill resource never depletes',
    category: 'Player',
    valueType: 'int32',
    infiniteValue: 9999,
    tags: ['infinite', 'toggle'],
  }),
  mk({
    id: 'edit-defense',
    name: 'Edit Defense',
    description: 'Modify damage reduction stat',
    category: 'Stats',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 10 },
    tags: ['stepper'],
  }),
  mk({
    id: 'super-damage-cd',
    name: 'Super Damage / One-Hit Kills',
    description: 'Massively boosts outgoing damage',
    category: 'Player',
    valueType: 'float',
    infiniteValue: 9999,
    tags: ['multiplier'],
  }),
  mk({
    id: 'edit-selected-money-cd',
    name: 'Edit Selected Item/Money Amount',
    description: 'Modify the currently selected inventory stack or currency',
    category: 'Stats',
    valueType: 'int32',
    defaultValue: 0,
    normalValues: { min: 0, max: 999999 },
    tags: ['stepper'],
  }),
  mk({
    id: 'freeze-daytime-cd',
    name: 'Freeze Daytime',
    description: 'Stops the in-game clock',
    category: 'Game',
    valueType: 'bool',
    infiniteValue: 1,
    tags: ['toggle'],
  }),
  mk({
    id: 'game-speed-cd',
    name: 'Game Speed',
    description: 'Modify overall simulation pacing',
    category: 'Game',
    valueType: 'float',
    defaultValue: 1.0,
    normalValues: { min: 0.1, max: 5 },
    tags: ['stepper', 'multiplier'],
  }),
];

// ============================================================================
// GAME CONFIGURATIONS
// ============================================================================

export const PALWORLD_CONFIG: GameConfig = {
  gameId: 'palworld',
  name: 'Palworld',
  executable: 'Palworld-Win64-Shipping.exe',
  aliases: ['Palworld.exe'],
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'stats', name: 'Stats' },
    { id: 'weapons', name: 'Weapons' },
    { id: 'enemies', name: 'Enemies' },
    { id: 'game', name: 'Game' },
    { id: 'physics', name: 'Physics' },
  ],
  cheats: palworldCheats,
  connectionBaseline: 4,
  description: 'Monster taming and crafting game with online multiplayer (cheat support: solo mode only)',
  releaseDate: '2024-01-19',
  lastUpdated: new Date('2026-07-08'),
  images: steamImages(1623730),
  pinnedCheatIds: ['infinite-player-health', 'infinite-stamina', 'instant-capture'],
};

export const ATOMFALL_CONFIG: GameConfig = {
  gameId: 'atomfall',
  name: 'Atomfall',
  executable: 'Atomfall.exe',
  aliases: ['Atomfall_dx12.exe'],
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'weapons', name: 'Weapons' },
    { id: 'game', name: 'Game' },
  ],
  cheats: atomfallCheats,
  connectionBaseline: 2,
  description: 'Post-apocalyptic action-adventure with Xbox Live integration',
  lastUpdated: new Date('2026-07-08'),
  images: steamImages(2075450),
  pinnedCheatIds: ['infinite-health', 'infinite-stamina', 'free-crafting'],
};

export const STARDEW_VALLEY_CONFIG: GameConfig = {
  gameId: 'stardew-valley',
  name: 'Stardew Valley',
  executable: 'StardewValley.exe',
  aliases: ['Stardew Valley.exe'],
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'console-command',
  dataType: 'int32',
  categories: [
    { id: 'currency', name: 'Currency' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'stats', name: 'Stats' },
    { id: 'relationships', name: 'Relationships' },
    { id: 'world', name: 'World' },
  ],
  cheats: stardewValleyCheats,
  connectionBaseline: 5,
  description: 'Farming simulation with built-in console commands (1.6.0+)',
  lastUpdated: new Date('2026-07-08'),
  images: steamImages(413150),
  pinnedCheatIds: ['set-money', 'teleport'],
};

export const AVOWED_CONFIG: GameConfig = {
  gameId: 'avowed',
  name: 'Avowed',
  executable: 'Avowed.exe',
  platform: 'xbox-game-pass',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'stats', name: 'Stats' },
    { id: 'weapons', name: 'Weapons' },
  ],
  cheats: avowedCheats,
  connectionBaseline: 0,
  description: 'Obsidian RPG with full cheat support via memory scanning',
  lastUpdated: new Date('2026-07-08'),
  images: steamImages(2457220),
  pinnedCheatIds: ['god-mode', 'infinite-essence'],
};

export const UNDISPUTED_CONFIG: GameConfig = {
  gameId: 'undisputed',
  name: 'Undisputed',
  executable: 'Undisputed.exe',
  // Confirmed live: process path is under WindowsApps\DeepSilver.Undisputed_* — Microsoft
  // Store/Xbox packaging, not Steam.
  platform: 'xbox-game-pass',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'career', name: 'Career' },
    { id: 'stats', name: 'Stats' },
    { id: 'enemies', name: 'Enemies' },
    { id: 'game', name: 'Game' },
  ],
  cheats: undisputedCheats,
  connectionBaseline: 7, // Measured 2026-07-08 during offline tutorial — see game-connection-baselines.ts
  description: 'Boxing simulation with stat and career mode cheats',
  lastUpdated: new Date('2026-07-08'),
  images: steamImages(1148810), // Steam art used for header/icon even for the Game Pass build — cosmetic only
  pinnedCheatIds: ['unlimited-health', 'infinite-stamina-boxing'],
};

export const DREDGE_CONFIG: GameConfig = {
  gameId: 'dredge',
  name: 'Dredge',
  executable: 'Dredge.exe',
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'inventory', name: 'Inventory' },
    { id: 'currency', name: 'Currency' },
    { id: 'boat', name: 'Boat' },
  ],
  cheats: dredgeCheats,
  connectionBaseline: 0,
  description: 'Indie horror fishing game with progression cheats',
  lastUpdated: new Date('2026-07-08'),
  images: steamImages(1562430),
  pinnedCheatIds: ['god-mode-dredge', 'unlimited-money-dredge'],
};

export const CRIMSON_DESERT_CONFIG: GameConfig = {
  gameId: 'crimson-desert',
  name: 'Crimson Desert',
  executable: 'CrimsonDesert.exe',
  platform: 'steam',
  cheatsSupported: true,
  cheatDiscoveryType: 'memory-scan',
  dataType: 'int32',
  categories: [
    { id: 'player', name: 'Player' },
    { id: 'stats', name: 'Stats' },
    { id: 'game', name: 'Game' },
  ],
  cheats: crimsonDesertCheats,
  connectionBaseline: 0,
  description: 'Pearl Abyss action-adventure with stat modification support',
  lastUpdated: new Date('2026-07-08'),
  // No confirmed Steam AppID yet (pre-release at last verification) — UI falls back to a gradient placeholder.
  pinnedCheatIds: ['unlimited-health-cd', 'unlimited-stamina-cd'],
};

// ============================================================================
// REGISTRY EXPORTS
// ============================================================================

export const ALL_GAMES = [
  PALWORLD_CONFIG,
  ATOMFALL_CONFIG,
  STARDEW_VALLEY_CONFIG,
  AVOWED_CONFIG,
  UNDISPUTED_CONFIG,
  DREDGE_CONFIG,
  CRIMSON_DESERT_CONFIG,
];
