/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * A live attach to a target process, scan-mechanics only (no policy — see
 * module doc). Wraps the handle in `Arc<Mutex<Option<...>>>` so it can be
 * shared with a background `Task` while still allowing an explicit
 * `detach()` from JS that releases the handle immediately (RAII `Drop`
 * still guarantees `CloseHandle` even if `detach()` is never called).
 *
 * Security note (mission §23): this class is exported for use by trusted
 * Electron main-process code only — it is Stage 2 foundation plumbing, not
 * a renderer-facing API. The existing game-scoped authority boundary
 * (attach authorization, protected-target blocklist, online-guard) remains
 * entirely in TypeScript and must gate every real call site that
 * constructs a `NativeScanTarget`; this class itself performs no such
 * policy check, by design (mechanics vs. policy separation).
 */
export declare class NativeScanTarget {
  /**
   * Attaches to `pid` with a read-only handle
   * (`PROCESS_QUERY_LIMITED_INFORMATION | PROCESS_VM_READ`).
   */
  static attach(pid: number): NativeScanTarget
  get pid(): number
  /**
   * Releases the underlying handle immediately rather than waiting for
   * this object to be garbage-collected. Safe to call more than once.
   */
  detach(): void
  isAttached(): boolean
  /**
   * `"open"` if the process is still running, `"exited"` if it has
   * terminated, per a fresh `GetExitCodeProcess` check (not cached).
   */
  status(): string
  /**
   * `"x64"` | `"x86_on_wow64"` | `"unknown"` — see
   * `solith_scanner_core::target::TargetArchitecture`. Real positive
   * (`x86_on_wow64`) validation against an actual 32-bit target process
   * is a documented, not-yet-executed Stage 2 gap (no i686 Rust target is
   * installed in this environment) — see Stage 2 evidence doc 17.
   */
  architecture(): string
  pointerWidthBytes(): number | null
  /**
   * Enumerates every committed/reserved region in the target's address
   * space. Synchronous (region enumeration across the full user-mode
   * address space is bounded and fast in practice — see Stage 2
   * evidence doc 16 for measured timing); the read operation, which can
   * be arbitrarily large, is the one made async (see
   * `read_region_chunked`).
   */
  enumerateRegions(): Array<JsRegion>
  /**
   * Reads `region` (as returned by `enumerate_regions`, or a
   * caller-constructed synthetic region for testing) in full, chunk by
   * chunk, honestly reporting completeness. Runs on napi's worker-thread
   * pool — does not block the JS event loop for the read's duration
   * (mission §14). `cancellation.cancel()` may be called from JS at any
   * time while the returned Promise is pending; `progress.snapshot()`
   * may be polled at any time for a live view of work completed so far.
   */
  readRegionChunked(region: JsRegion, chunkSizeBytes: bigint, overlapBytes: bigint, cancellation: ScanCancellationHandle, progress: ScanProgressHandle): Promise<JsReadRegionOutcome>
  /**
   * Convenience wrapper: enumerates regions, applies the default
   * writable-value-scan policy (mission §8's separation preserved —
   * this is one named policy, not baked into enumeration), and reads
   * every selected region. Exists so Stage 2's own tests/benchmarks
   * don't need to hand-roll policy application from JS; a future scan
   * mode is expected to call `enumerate_regions()` +
   * `read_region_chunked()` per-region directly with its own policy.
   */
  defaultRegionPolicySummary(): Array<JsRegion>
  /**
   * Scans `region` for an exact match of the given primitive value.
   * Runs on napi's worker-thread pool (mission §3.13's async
   * requirement) — see `read_region_chunked` above for the same
   * cancellation/progress contract, which this reuses unchanged.
   *
   * `primitiveType`: one of "i8","u8","i16","u16","i32","u32","i64",
   * "u64","f32","f64". `alignment`: "bytewise" (default/recommended) or
   * "aligned_to_type". `valueNumber`/`valueBigint`: exactly one must be
   * supplied, per `primitiveType` (see module doc's value contract).
   */
  scanExact(region: JsRegion, primitiveType: string, valueNumber: number | undefined | null, valueBigint: bigint | undefined | null, alignment: string, chunkSizeBytes: bigint, overlapBytes: bigint, maxResults: bigint | undefined | null, cancellation: ScanCancellationHandle, progress: ScanProgressHandle): Promise<JsExactScanOutcome>
}

export declare class ScanCancellationHandle {
  constructor()
  cancel(): void
  get isCancelled(): boolean
}

export declare class ScanProgressHandle {
  constructor()
  /**
   * Current snapshot of the in-flight (or completed) operation's
   * metrics. Safe to call at any time, including before the operation
   * starts (returns all-zero metrics) and after it finishes (returns the
   * final metrics, unchanged thereafter).
   */
  snapshot(): JsProgress
}

/**
 * Echoes a `BigInt` argument back unchanged, as a `u64`, proving the napi
 * boundary carries 64-bit values end to end without ever routing through a
 * lossy JS `Number` — this is the property Stage 1's D06 (int64 precision
 * loss) needs the *value* half of, generalizing the pattern the
 * TypeScript scanner today only applies to addresses (`readPointer`).
 * Exposed as a standalone diagnostic function (not tied to a real scan)
 * because no real Windows user-mode address exceeds
 * `Number.MAX_SAFE_INTEGER` in practice (the 48-bit address space ceiling
 * is well under 2^53) — the property this proves is about API discipline,
 * not about a magnitude no real attach would ever produce.
 */
export declare function debugEchoU64(value: bigint): bigint

export interface JsChunkReadResult {
  chunkBase: bigint
  requestedSize: bigint
  /**
   * One of: "success", "partial_read", "access_denied", "target_exited",
   * "invalid_address", "os_error", "resource_limit", "cancelled".
   */
  status: string
  bytesReadIfPartial?: bigint
  data: Buffer
}

export interface JsCompleteness {
  /**
   * One of: "complete", "complete_with_skipped_regions", "cancelled",
   * "process_exited", "read_error_limit", "resource_limit", "failed".
   */
  state: string
  atByte?: bigint
  skipped?: Array<JsSkippedRange>
  failedReason?: string
}

export interface JsExactScanOutcome {
  matches: Array<JsScanMatch>
  metrics: JsProgress
  completeness: JsCompleteness
}

export interface JsProgress {
  regionsTotal: number
  regionsConsidered: number
  regionsRead: number
  regionsSkipped: number
  chunksRequested: number
  chunksRead: number
  chunksPartial: number
  chunksFailed: number
  bytesRequested: bigint
  bytesRead: bigint
  syscallCount: bigint
  elapsedMillis: bigint
}

export interface JsReadRegionOutcome {
  chunks: Array<JsChunkReadResult>
  metrics: JsProgress
  completeness: JsCompleteness
}

export interface JsRegion {
  baseAddress: bigint
  size: bigint
  allocationBase: bigint
  commitState: string
  kind: string
  isReadable: boolean
  isWritable: boolean
  isExecutable: boolean
  isGuard: boolean
  isNoaccess: boolean
  rawProtect: number
  rawType: number
}

export interface JsScanMatch {
  address: bigint
  /** One of the 10 canonical type strings ("i8".."f64"). */
  primitiveType: string
  /** Populated for every type except i64/u64. */
  valueNumber?: number
  /** Populated only for i64/u64 — exact, never routed through `f64`. */
  valueBigint?: bigint
}

export interface JsSkippedRange {
  baseAddress: bigint
  size: bigint
  reason: string
}
