/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * A native scan-session (mission §4.1/§4.14). See the module-level comment
 * above for the create-once/refine-many lifecycle and the leak-nothing
 * boundary discipline this class follows.
 */
export declare class NativeScanSession {
  constructor()
  /**
   * Establishes the `UNKNOWN_INITIAL` baseline (mission §4.4): opens a
   * fresh, session-owned handle to `pid` and captures every eligible
   * candidate across `regions` (as returned by
   * `NativeScanTarget.enumerateRegions()`, or a caller-constructed list)
   * per `alignment`. May be called exactly once per session instance.
   */
  createUnknownInitial(pid: number, regions: Array<JsRegion>, primitiveType: string, alignment: string, chunkSizeBytes: bigint, overlapBytes: bigint, maxCandidates: bigint | undefined | null, maxSnapshotBytes: bigint | undefined | null, maxSessionBytes: bigint | undefined | null, cancellation: ScanCancellationHandle, progress: ScanProgressHandle): Promise<JsRefineOutcome>
  /**
   * Re-reads the current candidate set and filters by `mode` (mission
   * §4.5-§4.8): one of `"changed"`, `"unchanged"`, `"increased"`,
   * `"decreased"`, `"increased_by"`, `"decreased_by"`, `"between"`.
   * `valueNumber`/`valueBigint` supply the delta for
   * `increased_by`/`decreased_by`; `minNumber`/`minBigint` and
   * `maxNumber`/`maxBigint` supply the inclusive bounds for `between` —
   * exactly one of the Number/BigInt pair per slot, per the session's own
   * primitive type (same value-duality contract as `scanExact`).
   */
  refine(mode: string, valueNumber: number | undefined | null, valueBigint: bigint | undefined | null, minNumber: number | undefined | null, minBigint: bigint | undefined | null, maxNumber: number | undefined | null, maxBigint: bigint | undefined | null, cancellation: ScanCancellationHandle, progress: ScanProgressHandle): Promise<JsRefineOutcome>
  /**
   * A bounded, deterministically-ordered page of the current candidate
   * set (mission §4.3/§4.14's pagination requirement) — synchronous,
   * since it is a plain in-memory slice, not a re-read of target memory.
   */
  getResults(offset: bigint, limit: number): Array<JsScanMatch>
  /**
   * Full generation history recorded so far (mission §4.9), oldest
   * first, bounded by `maxGenerationsRetained`.
   */
  generationHistory(): Array<JsGenerationRecord>
  /**
   * Current status snapshot, including a live (never cached)
   * stale-target check (mission §4.2).
   */
  status(): JsSessionStatus
  /**
   * Releases the session's handle and candidate storage immediately
   * (mission §4.15) rather than waiting for garbage collection. Safe to
   * call more than once, and safe to call before `createUnknownInitial`.
   */
  close(): void
  isInitialized(): boolean
  /**
   * Captures the session's current persistable-safe metadata (Stage 6
   * §6.9) as a JSON string — a live OS handle and raw candidate
   * addresses/values are never included (see
   * `solith_scanner_core::session_snapshot`'s module doc for why).
   * `target_executable_hint` is an optional, caller-supplied, unverified
   * display label. Purely in-memory; does not touch disk — pair with
   * `saveSessionSnapshot` to persist it.
   */
  exportSnapshotJson(targetExecutableHint?: string | undefined | null): string
}

/**
 * A live attach to a target process, scan-mechanics only (no policy — see
 * module doc). Wraps the handle in `Arc<Mutex<Option<...>>>` so it can be
 * shared with a background `Task` while still allowing an explicit
 * `detach()` from JS that releases the handle immediately (RAII `Drop`
 * still guarantees `CloseHandle` even if `detach()` is never called).
 *
 * Security note (mission §23): this class is exported for use by trusted
 * Electron main-process code only — it is Stage 2 foundation plumbing, not
 * a renderer-facing API. The existing game-scoped authority boundary
 * (attach authorization, protected-target blocklist, online-guard) remains
 * entirely in TypeScript and must gate every real call site that
 * constructs a `NativeScanTarget`; this class itself performs no such
 * policy check, by design (mechanics vs. policy separation).
 */
export declare class NativeScanTarget {
  /**
   * Attaches to `pid` with a read-only handle
   * (`PROCESS_QUERY_LIMITED_INFORMATION | PROCESS_VM_READ`).
   */
  static attach(pid: number): NativeScanTarget
  get pid(): number
  /**
   * Releases the underlying handle immediately rather than waiting for
   * this object to be garbage-collected. Safe to call more than once.
   */
  detach(): void
  isAttached(): boolean
  /**
   * `"open"` if the process is still running, `"exited"` if it has
   * terminated, per a fresh `GetExitCodeProcess` check (not cached).
   */
  status(): string
  /**
   * `"x64"` | `"x86_on_wow64"` | `"unknown"` — see
   * `solith_scanner_core::target::TargetArchitecture`. Real positive
   * (`x86_on_wow64`) validation against an actual 32-bit target process
   * is a documented, not-yet-executed Stage 2 gap (no i686 Rust target is
   * installed in this environment) — see Stage 2 evidence doc 17.
   */
  architecture(): string
  pointerWidthBytes(): number | null
  /**
   * Enumerates every committed/reserved region in the target's address
   * space. Synchronous (region enumeration across the full user-mode
   * address space is bounded and fast in practice — see Stage 2
   * evidence doc 16 for measured timing); the read operation, which can
   * be arbitrarily large, is the one made async (see
   * `read_region_chunked`).
   */
  enumerateRegions(): Array<JsRegion>
  /**
   * Reads `region` (as returned by `enumerate_regions`, or a
   * caller-constructed synthetic region for testing) in full, chunk by
   * chunk, honestly reporting completeness. Runs on napi's worker-thread
   * pool — does not block the JS event loop for the read's duration
   * (mission §14). `cancellation.cancel()` may be called from JS at any
   * time while the returned Promise is pending; `progress.snapshot()`
   * may be polled at any time for a live view of work completed so far.
   */
  readRegionChunked(region: JsRegion, chunkSizeBytes: bigint, overlapBytes: bigint, cancellation: ScanCancellationHandle, progress: ScanProgressHandle): Promise<JsReadRegionOutcome>
  /**
   * Convenience wrapper: enumerates regions, applies the default
   * writable-value-scan policy (mission §8's separation preserved —
   * this is one named policy, not baked into enumeration), and reads
   * every selected region. Exists so Stage 2's own tests/benchmarks
   * don't need to hand-roll policy application from JS; a future scan
   * mode is expected to call `enumerate_regions()` +
   * `read_region_chunked()` per-region directly with its own policy.
   */
  defaultRegionPolicySummary(): Array<JsRegion>
  /**
   * Scans `region` for an exact match of the given primitive value.
   * Runs on napi's worker-thread pool (mission §3.13's async
   * requirement) — see `read_region_chunked` above for the same
   * cancellation/progress contract, which this reuses unchanged.
   *
   * `primitiveType`: one of "i8","u8","i16","u16","i32","u32","i64",
   * "u64","f32","f64". `alignment`: "bytewise" (default/recommended) or
   * "aligned_to_type". `valueNumber`/`valueBigint`: exactly one must be
   * supplied, per `primitiveType` (see module doc's value contract).
   */
  scanExact(region: JsRegion, primitiveType: string, valueNumber: number | undefined | null, valueBigint: bigint | undefined | null, alignment: string, chunkSizeBytes: bigint, overlapBytes: bigint, maxResults: bigint | undefined | null, cancellation: ScanCancellationHandle, progress: ScanProgressHandle): Promise<JsExactScanOutcome>
  /**
   * Scans `region` for every occurrence of an exact raw byte sequence
   * (mission §5.3). `bytes` must not be empty.
   */
  scanBytes(region: JsRegion, bytes: Buffer, chunkSizeBytes: bigint, maxResults: bigint | undefined | null, firstMatchOnly: boolean | undefined | null, cancellation: ScanCancellationHandle, progress: ScanProgressHandle): Promise<JsPatternScanOutcome>
  /**
   * Scans `region` for `text`, encoded per `encoding` ("utf8" or
   * "utf16le") — mission §5.2. `caseSensitive` (default-recommended:
   * true) controls ASCII-only case folding (module doc for the
   * justification); `nullTerminator` is "none" (match the content
   * anywhere) or "required" (match only when immediately followed by a
   * real encoding-native null terminator).
   */
  scanString(region: JsRegion, text: string, encoding: string, caseSensitive: boolean, nullTerminator: string, chunkSizeBytes: bigint, maxResults: bigint | undefined | null, firstMatchOnly: boolean | undefined | null, cancellation: ScanCancellationHandle, progress: ScanProgressHandle): Promise<JsPatternScanOutcome>
  /**
   * Scans `region` for the AOB pattern `pattern` (mission §5.4's
   * grammar: whitespace-separated exact-byte/`??`/`?`/`*`/nibble-wildcard
   * tokens — see `solith_scanner_core::pattern::parse_aob`'s doc). A
   * malformed pattern is rejected with a stable
   * `invalid_hex_token:`/`malformed_wildcard:`/`empty_pattern:`/
   * `unsupported_token:`/`invalid_separator:`-prefixed error, synchronously,
   * before any async work begins.
   */
  scanAob(region: JsRegion, pattern: string, chunkSizeBytes: bigint, maxResults: bigint | undefined | null, firstMatchOnly: boolean | undefined | null, cancellation: ScanCancellationHandle, progress: ScanProgressHandle): Promise<JsPatternScanOutcome>
}

export declare class ScanCancellationHandle {
  constructor()
  cancel(): void
  get isCancelled(): boolean
}

export declare class ScanProgressHandle {
  constructor()
  /**
   * Current snapshot of the in-flight (or completed) operation's
   * metrics. Safe to call at any time, including before the operation
   * starts (returns all-zero metrics) and after it finishes (returns the
   * final metrics, unchanged thereafter).
   */
  snapshot(): JsProgress
}

/**
 * Echoes a `BigInt` argument back unchanged, as a `u64`, proving the napi
 * boundary carries 64-bit values end to end without ever routing through a
 * lossy JS `Number` — this is the property Stage 1's D06 (int64 precision
 * loss) needs the *value* half of, generalizing the pattern the
 * TypeScript scanner today only applies to addresses (`readPointer`).
 * Exposed as a standalone diagnostic function (not tied to a real scan)
 * because no real Windows user-mode address exceeds
 * `Number.MAX_SAFE_INTEGER` in practice (the 48-bit address space ceiling
 * is well under 2^53) — the property this proves is about API discipline,
 * not about a magnitude no real attach would ever produce.
 */
export declare function debugEchoU64(value: bigint): bigint

/**
 * Deletes the snapshot named `snapshot_id` under `dir`. Idempotent — a
 * missing file is not an error.
 */
export declare function deleteSessionSnapshot(dir: string, snapshotId: string): void

export interface JsAobValidation {
  valid: boolean
  byteLength?: number
  errorKind?: string
  errorMessage?: string
}

export interface JsChunkReadResult {
  chunkBase: bigint
  requestedSize: bigint
  /**
   * One of: "success", "partial_read", "access_denied", "target_exited",
   * "invalid_address", "os_error", "resource_limit", "cancelled".
   */
  status: string
  bytesReadIfPartial?: bigint
  data: Buffer
}

export interface JsCompleteness {
  /**
   * One of: "complete", "complete_with_skipped_regions", "cancelled",
   * "process_exited", "read_error_limit", "resource_limit", "failed".
   */
  state: string
  atByte?: bigint
  skipped?: Array<JsSkippedRange>
  failedReason?: string
}

export interface JsExactScanOutcome {
  matches: Array<JsScanMatch>
  metrics: JsProgress
  completeness: JsCompleteness
  /**
   * Stage 6 §6.3's shared authoritative-absence rule, evaluated once here
   * so callers never have to re-derive "zero matches AND fully covered"
   * themselves: true iff `matches` is empty AND `completeness` is
   * `Complete`. False for every other completeness state, even with
   * zero matches — absence is not authoritative there.
   */
  isAuthoritativeAbsence: boolean
}

export interface JsGenerationRecord {
  generation: number
  modeLabel: string
  inputCandidateCount: bigint
  outputCandidateCount: bigint
  bytesReread: bigint
  skippedReads: bigint
  completeness: JsCompleteness
  durationMillis: bigint
}

export interface JsPatternMatch {
  address: bigint
  length: number
}

export interface JsPatternScanOutcome {
  /**
   * One of "raw_bytes", "utf8", "utf16le", "aob" — echoes which Stage 5
   * surface produced this result (mission §5.10's "pattern/string type"
   * result field).
   */
  kind: string
  matches: Array<JsPatternMatch>
  metrics: JsProgress
  completeness: JsCompleteness
  /**
   * Stage 6 §6.3's shared authoritative-absence rule (see
   * `JsExactScanOutcome`'s field of the same name for the exact
   * definition) — identical semantics here for string/byte/AOB scans.
   */
  isAuthoritativeAbsence: boolean
}

export interface JsProgress {
  regionsTotal: number
  regionsConsidered: number
  regionsRead: number
  regionsSkipped: number
  chunksRequested: number
  chunksRead: number
  chunksPartial: number
  chunksFailed: number
  bytesRequested: bigint
  bytesRead: bigint
  syscallCount: bigint
  elapsedMillis: bigint
}

export interface JsReadRegionOutcome {
  chunks: Array<JsChunkReadResult>
  metrics: JsProgress
  completeness: JsCompleteness
}

export interface JsRefineOutcome {
  generation: number
  inputCandidateCount: bigint
  outputCandidateCount: bigint
  bytesReread: bigint
  skippedReads: bigint
  completeness: JsCompleteness
  durationMillis: bigint
}

export interface JsRegion {
  baseAddress: bigint
  size: bigint
  allocationBase: bigint
  commitState: string
  kind: string
  isReadable: boolean
  isWritable: boolean
  isExecutable: boolean
  isGuard: boolean
  isNoaccess: boolean
  rawProtect: number
  rawType: number
}

export interface JsScanMatch {
  address: bigint
  /** One of the 10 canonical type strings ("i8".."f64"). */
  primitiveType: string
  /** Populated for every type except i64/u64. */
  valueNumber?: number
  /** Populated only for i64/u64 — exact, never routed through `f64`. */
  valueBigint?: bigint
}

export interface JsSessionSnapshotInfo {
  schemaVersion: number
  scannerCoreVersion: string
  primitiveType: string
  alignment: string
  processPid: number
  targetExecutableHint?: string
  generation: number
  candidateCount: bigint
  lastCompletenessLabel: string
  takenAtUnixMillis: bigint
  /**
   * One of `"inactive"`, `"stale"`, `"recoverable_metadata"` (Stage 6
   * §6.12) — never `"live"`. A caller must always perform an explicit,
   * user-initiated reattach (a fresh `createUnknownInitial`) even when
   * this is `"recoverable_metadata"`; nothing here constructs a session.
   */
  recoveryStatus: string
}

export interface JsSessionStatus {
  pid: number
  primitiveType: string
  alignment: string
  generation: number
  candidateCount: bigint
  candidateMemoryBytes: bigint
  lastCompleteness: JsCompleteness
  /**
   * `false` once the session's target process has exited — checked live
   * via `GetExitCodeProcess` on every call, never cached (mission §4.2).
   */
  isStale: boolean
}

export interface JsSkippedRange {
  baseAddress: bigint
  size: bigint
  reason: string
}

/**
 * Loads, fully validates, and classifies the recovery status of the
 * snapshot named `snapshot_id` under `dir` — never constructs a live
 * session (Stage 6 §6.12).
 */
export declare function loadSessionSnapshotInfo(dir: string, snapshotId: string): JsSessionSnapshotInfo

/**
 * Validates `snapshot_json` (schema version + checksum) and atomically
 * writes it to `<dir>/<snapshot_id>.solith-session-snapshot.json`
 * (temp-file-then-rename). `snapshot_id` must be a bare identifier
 * (ASCII letters/digits/`_`/`-` only) — path separators and `..` are
 * rejected outright (Stage 6 §6.24's "no arbitrary path traversal").
 */
export declare function saveSessionSnapshot(dir: string, snapshotId: string, snapshotJson: string): string

/**
 * Parses `pattern` per `solith_scanner_core::pattern::parse_aob`'s grammar
 * and reports the outcome without performing any scan. Never throws — a
 * malformed pattern is reported as `{ valid: false, errorKind, errorMessage }`
 * rather than a rejected promise, since this is a pure classification query,
 * not a scan request.
 */
export declare function validateAobPattern(pattern: string): JsAobValidation
