name: OSV-Scanner

on:
  pull_request:
    branches: [master]
  merge_group:
    branches: [master]
  push:
    branches: [master]
  schedule:
    - cron: "37 11 * * 1"
  workflow_dispatch:

jobs:
  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.5.0
    with:
      scan-args: |-
        --include-git-root
        -r
        ./

  scan-full:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.5.0
    with:
      scan-args: |-
        --include-git-root
        -r
        ./
